### ISSUE TITLE
Web UI can't be opened on ubuntu installed on vitualbox 

### ISSUE THREAD

**Issue by xinnnxinnn** [openthread/borderrouter#101]
Hi,
when I followed the steps showed in "https://github.com/openthread/borderrouter/wiki" and try to build the environment of border router on ubuntu(virtual machine) with cc2538(NCP), I can't open web page "http://127.0.0.1:8080/web/frontend/app/#".

The environment:
1.CC2538 driver has been installed.
root@robot-VirtualBox:/home/robot/tinyara/borderrouter-master# ls /dev | grep ttyUSB
ttyUSB0
ttyUSB1

2. ./scrip/server
Current platform is ubuntu
* Applying /etc/sysctl.d/10-console-messages.conf ...
kernel.printk = 4 4 1 7
* Applying /etc/sysctl.d/10-ipv6-privacy.conf ...
net.ipv6.conf.all.use_tempaddr = 2
net.ipv6.conf.default.use_tempaddr = 2
* Applying /etc/sysctl.d/10-kernel-hardening.conf ...
kernel.kptr_restrict = 1
* Applying /etc/sysctl.d/10-link-restrictions.conf ...
fs.protected_hardlinks = 1
fs.protected_symlinks = 1
* Applying /etc/sysctl.d/10-magic-sysrq.conf ...
kernel.sysrq = 176
* Applying /etc/sysctl.d/10-network-security.conf ...
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.all.rp_filter = 1
net.ipv4.tcp_syncookies = 1
* Applying /etc/sysctl.d/10-ptrace.conf ...
kernel.yama.ptrace_scope = 1
* Applying /etc/sysctl.d/10-zeropage.conf ...
vm.mmap_min_addr = 65536
* Applying /etc/sysctl.d/60-otbr-ip-forward.conf ...
net.ipv6.conf.all.forwarding = 1
net.ipv4.ip_forward = 1
* Applying /etc/sysctl.d/99-sysctl.conf ...
active
active
activating

3.The network proxy of the system and firefox has been closed.

But when I input  "http://127.0.0.1:8080/web/frontend/app/#" in firefox, the web page returns "Unbale to connect". I can't find the fail reason and  could you please help me to find what causes this failure?
Thanks a lot!

**Comment by LeZhang2016** [comment]
I think the default port to Web server is` 80` in latest version. You could try to change the  `http://127.0.0.1` as the Web UI's URL.

**Comment by xinnnxinnn** [comment]
@LeZhang2016 
Yeah, thank you so much!

**Comment by xinnnxinnn** [comment]
Hi @LeZhang2016，
I have build a network with border router(leader),  the question is that
1. whether the host(ubuntu) can get a reply from the joiner(Thread device)  with ping request? Now I have tried ping request, but there is no reply. In addition, there is no "Has Route" TLV  which contains the external network information in Thread packets.
2.Do I have to manually configure tayga(refer to https://github.com/openthread/borderrouter/wiki/NAT64) ? I find that NAT64 is configured and started in script/setup and script/server.

The network information is
**> root@robot-VirtualBox:/home/robot/tinyara/borderrouter-master# wpanctl status**
wpan0 => [
	"NCP:State" => "associated"
	"Daemon:Enabled" => true
	"NCP:Version" => "OPENTHREAD/0.01.00; CC2538; Sep  6 2017 15:28:58"
	"Daemon:Version" => "0.08.00d (; Sep  1 2017 13:39:06)"
	"Config:NCP:DriverName" => "spinel"
	"NCP:HardwareAddress" => [060D7F1B00124B00]
	"NCP:Channel" => 18
	"Network:NodeType" => "leader"
	"Network:Name" => "OpenThreadDemo"
	"Network:XPANID" => 0x1111111122222222
	"Network:PANID" => 0x1235
	"IPv6:LinkLocalAddress" => "fe80::e445:97ee:858b:8b5b"
	"IPv6:MeshLocalAddress" => "fd11:1111:1122:0:4d67:9d1e:b674:883"
	"IPv6:MeshLocalPrefix" => "fd11:1111:1122::/64"
	"com.nestlabs.internal:Network:AllowingJoin" => false
]

**> root@robot-VirtualBox:/home/robot/tinyara/borderrouter-master# ifconfig**
eth0      Link encap:Ethernet  HWaddr 08:00:27:34:b0:af  
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe34:b0af/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:359 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1036 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:68753 (68.7 KB)  TX bytes:171619 (171.6 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:618 errors:0 dropped:0 overruns:0 frame:0
          TX packets:618 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:83225 (83.2 KB)  TX bytes:83225 (83.2 KB)

nat64     Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:500 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

wpan0     Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet6 addr: fd11:1111:1122:0:4d67:9d1e:b674:883/64 Scope:Global
          inet6 addr: fe80::e445:97ee:858b:8b5b/64 Scope:Link
          inet6 addr: fd11:22::e445:97ee:858b:8b5b/64 Scope:Global
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1280  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:43 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:500 
          RX bytes:0 (0.0 B)  TX bytes:4128 (4.1 KB)

When I use the cmd "ping fd11:22:0:0:ff0:b307:a0:625e" on ubuntu terminal, the prompt is "ping: unknown host fd11:22:0:0:ff0:b307:a0:625e", where  "fd11:22:0:0:ff0:b307:a0:625e" is the address of the joiner(Thread device).

**Comment by LeZhang2016** [comment]
Hi @xinnnxinnn,
User could PING the nodes in Thread network from the border router host side.
You could use command `ping6 fd11:22:0:0:ff0:b307:a0:625e` and try again.
NAT64 is configured automatically during setup the border router, it can not be set manually.

**Comment by xinnnxinnn** [comment]
Hi @LeZhang2016，
I found that when use ping request cmd from border router host side to the internal Thread node, the source address is the inet6 addr of wpan0.  It seems that the Thread node can only access the border router but not the external network like www.baidu.com. 
My question is that:
1. Does the Thread device can access to the extenal network? 
2.  Does wpan0 build a mapping with WAN (WiFi, Ethernet) interfaces? How can I verify it?
3. Where can I download  commissioner app to verify the figure 2 in [](https://github.com/openthread/borderrouter) ?
Thank you so much for your reply.

**Comment by xinnnxinnn** [comment]
Hi @LeZhang2016，
I found that when use ping request cmd from border router host side to the internal Thread node, the source address is the inet6 addr of wpan0. It seems that the Thread node can only access the border router but not the external network like www.baidu.com.
My question is that:
1. Does the Thread device can access to the extenal network?
2. Does wpan0 build a mapping with WAN (WiFi, Ethernet) interfaces? How can I verify it?
3. Where can I download commissioner app to verify the figure 2 in https://github.com/openthread/borderrouter ?
Thank you so much for your reply.

**Comment by LeZhang2016** [comment]
Hi @xinnnxinnn,
1. Thread device could access the external network via border router. You could try to execute`ping6 64:ff9b::103.235.46.39` to reach the `baidu` website.
2. There is no mapping between the wpan0 and WAN, but border router is enabled the IPv6 and IPv4 forwarding between the interfaces, so the IP packets can be forwarded between wpan0 and wan.
3. You could download the commissioner app from here https://play.google.com/store/apps/details?id=org.threadgroup.commissioner.

**Comment by LeZhang2016** [comment]
@xinnnxinnn 
I think the previous link of the commissioner app can not be used successfully, so you'd better change this one which has been verified.
http://intrepid.io/ota/ThreadCommissionerAndroid/

**Comment by xinnnxinnn** [comment]
Hi @LeZhang2016，
Oh, thanks a lot for your help, I will try to use the commissioner app.

**Comment by xinnnxinnn** [comment]
Hi @LeZhang2016，
Sorry to disturb you for serval times ^_^
I build a local area network with a mobile(installed with commissioner app),a local PC and a virtual machine(Ubuntu, as a border router) installed on that local PC.
The topology of the Thread network is: boder router(leader)<---->router(internal Thread device).
I have two questions:
1.  Now  I can use wpan0 to communicate with local PC with "ping6 -I wpan0 2001:db8:1:ffff::192.168.0.100" for I changed the tayga.conf like this: 
ipv6-addr 2001:db8:1::2
prefix 2001:db8:1:ffff::/96
But I can't find a method to verify that whether the internal Thread device(router) can communiccate with external  network(like local PC or commissioner) by ping or other means. 
2.  when I connect the commissioner app with border router, there may be  two prompts,  one is "Thread admin password"  and the other one is "Enter join passphrase" with "EUI" and "Passphrase". I tr
ied to input "123456" for "Thread admin password" , it failed, and I also feel confused that which adrress is EUI is represented for and what's the passphrase. 
Could you please answer these two questions？ Thank you!

**Comment by bukepo** [comment]
1. If the internal Thread device is of CLI version, you may use the [`ping`](https://github.com/openthread/openthread/tree/master/src/cli#ping-ipaddr-size-count-interval) command.
2. You may need refer to the Thread protocol. *Thread admin password* is set at the Web GUI when you form the network. *Join passphrase* should be the same when you start joining on the joiner. That is, if you type `joiner start 654321` on CLI, then the *join passphrase* should be *654321* on the commissioner app.

**Comment by bukepo** [comment]
If you have additional questions, you may open new issues or post on [Google Group](https://groups.google.com/forum/#!forum/openthread-users).
