### ISSUE TITLE
Setting PSKc passphrases via the CLI

### ISSUE THREAD

**Issue by Vyrastas** [openthread/borderrouter#108]
Opening this issue as part of the Wiki deprecation.

Currently, PSKc passphrases cannot be set via the CLI. To set a PSKc passphrase for commissioning, you must use the "Form" Web UI when creating a new Thread network using OTBR.

This will eventually be noted in a Thread Commissioning guide using the OTBR Web UI, tracked in #62 .  At that time we can close, or leave it open if this is functionality that should eventually be available via the CLI.

**Comment by bukepo** [comment]
PSKc must be set before forming Thread network. Did you try setting PSKc after the network is formed?

**Comment by Vyrastas** [comment]
No... this is an issue we had on the Wiki that I just copied over here.  Are you saying the PSKc can be set via the CLI if it's done prior to forming the network?

**Comment by bukepo** [comment]
Yes, because I have been using CLI to set PSKc when I test border router.

**Comment by Vyrastas** [comment]
Alright, well then this isn't an issue.  I'll add this to the content on openthread.io.
