### ISSUE TITLE
Thread Commissioning App compatibility

### ISSUE THREAD

**Issue by Vyrastas** [openthread/borderrouter#109]
Opening this issue as part of the Wiki deprecation.

Currently, the public release of the Thread Commissioning App cannot be used for testing with OTBR.

This will eventually be noted in a Thread Commissioning guide using the OTBR Web UI, tracked in #62 . At that time we can close, or leave it open until we get the public release of the Thread Commissioning App updated.

**Comment by beriberikix** [comment]
Per #62, this should be fixed

**Comment by Vyrastas** [comment]
Thanks for letting me know, I'll download and verify.

**Comment by Vyrastas** [comment]
Confirmed that the update fixed this problem, closing.

**Comment by rohithanayady** [comment]
Why Thread Commissioning App takes more time to add the new devices into the Thread network after scanned the QR code
