### ISSUE TITLE
How to contribute to the Wiki on openthread.io?

### ISSUE THREAD

**Issue by DuaneEllis-TI** [openthread/borderrouter#112]
We (TI) are getting ready to push up border router support for the Beagle Bone Black  - and want to know what is the process to contribute additional information in the border router wiki on the openthread.io? wiki page?

Thanks.

**Comment by jwhui** [comment]
Submitting an issue is sufficient for openthread.io:

For future reference, from https://openthread.io/resources/

> If you would like to contribute to openthread.io, please submit an issue to the Issue Tracker, explaining your proposed contribution. A member of the OpenThread team will work with you to get your content added to the site.

**Comment by Vyrastas** [comment]
@DuaneEllis-TI I can help, what kind of documentation will it be, exactly?

**Comment by DuaneEllis-TI** [comment]
Sorry for the delay - we had some internal reviews I needed to complete - 

Please check out this pull request:
* https://github.com/openthread/borderrouter/pull/115

In the "docs" directory are two MS Word documents that contain the basic set of changes that we are proposing for the wiki. 

What I don't know - is the raw format & etc - for the wiki entries. Thus in the mean time I wrote the changes up in MS Word.  I would consider these changes "in very-rough-draft" form.

**Comment by Vyrastas** [comment]
No worries @DuaneEllis-TI , thanks for attaching those docs.

This is our first external contribution to the new site, so lucky you, you get to be the guinea pig to help us iron out the contribution process.  :)  We'll make contribution updates more clear after this.

If you would, please send me an email at jbumgardner [at] google [dot] com and we'll go from there.  I'm thinking the best method is to put your draft content into a Google Doc which we can collaborate on and refine together.  Once you're happy with it, I'll add it to the site with attribution.

**Comment by jwhui** [comment]
New docs are published at: https://openthread.io/guides/border_router/beaglebone_black
