### ISSUE TITLE
Graphical user interface for WiFi management

### ISSUE THREAD

**Issue by prfi** [openthread/borderrouter#121]
I've made pull request with support for Network Manager as a first step for simplifying WiFi management. I'm going to continue my work in this area and currently I want ask you about help to make a decision what is the approach.

There are available two approaches:
1) Extend an existing Border Router control panel. There will be supported only basic functionalities that allow to connect and disconnect, setup AP, setup password.
2) Use some available OpenSource WebGUI for Network Manager (e.g. https://github.com/mk-fg/NetworkManager-WiFi-WebUI?files=1)

What do you think about this idea? Do you have any opinion about that?

**Comment by jwhui** [comment]
@prfi, adding NetworkManager support is a great enhancement!  Thanks for working to make that happen.

The example you noted (https://github.com/mk-fg/NetworkManager-WiFi-WebUI?files=1) has a WTFPL license.  Unfortunately, code released under the WTFPL cannot be included in Google open source projects.  If there are other open source web GUIs with a compatible license that you find interesting, we can consider those.

It might be nice to extend the existing OTBR web UI to maintain a more consistent user interface.

Thoughts?

**Comment by prfi** [comment]
Ok, then I will focus on adding simple configuration panel to current UI.

**Comment by jwhui** [comment]
Closing stale issue.
