### ISSUE TITLE
DHCPv6 PD doesn't work after dhcpcd5 update

### ISSUE THREAD

**Issue by prfi** [openthread/borderrouter#122]
I've noticed that from about week ago DHCPv6 PD doesn't work properly. Today I've spent some time on investigation this problem and I've found reason. Few days ago there were dhcpcd5 update in raspbian repository (from version: 1:6.11.5-1+rpt2 to version 1:6.11.5-1+rpt4). An update provide some fixes, unfortunatly one fix provides improvement that can be very harmful because it assume that every interface which first letter is equal to "w" is a wireless interface, so wpan0 is treated as wireless interface and dhcpcd5 can't get carrier for this interface, so it say that it is not connected and can't delegate IPv6 prefix to it. Below I've put mentioned change.

```
--- a/if.c
+++ b/if.c
@@ -534,7 +534,7 @@
                /* We reserve the 100 range for virtual interfaces, if and when
                 * we can work them out. */
                ifp->metric = 200 + ifp->index;
-               if (if_getssid(ifp) != -1) {
+               if (if_getssid(ifp) != -1 || *ifp->name == 'w') {
                        ifp->wireless = 1;
                        ifp->metric += 100;
                }
```

There is few options that allow us to solve this problem.
1) Because I haven't managed to install previous version from apt-get, there is an option to commit working DEB with dhcpcd5 to git repository and install it via `dpkg` during border router installation. It is the easiest solution. This option allow avoid similar situations in the future.
2) Second option is to inform an author and wait for fix (if he decide to fix it).

I've tried to fixit by changes in config file but unfortunatly I haven't found working solution. So I've decided to abandon this idea and ask what do you think about first solution that seems to be the most bullet proof solution?

**Comment by jwhui** [comment]
Resolved by #123.

**Comment by sjlongland** [comment]
Just stumbled on this today digging through the build scripts for OTBR.  It would seem the dangerous change has been reverted.  `6.11.5-1+rpt7` no longer contains this change.

**Comment by jwhui** [comment]
> Just stumbled on this today digging through the build scripts for OTBR. It would seem the dangerous change has been reverted. `6.11.5-1+rpt7` no longer contains this change.

@sjlongland , thanks for the update. Are you proposing any changes to this repo?

**Comment by sjlongland** [comment]
I'll try to test and see if the problem can be reproduced, but my hunch is that we may be able to revert commit 9a3406c440c764a9cc19a7d97c4e8f08d56a0b2d.

**Comment by martinzi** [comment]
Current dhcpcd version 8.1.2 installed from apt repository works fine. Changes introduced with #123 should be reverted as they cause PD to fail on RaspiOS Buster.
