### ISSUE TITLE
Joiner fails to join network with external commissioning

### ISSUE THREAD

**Issue by kyberpunk** [openthread/borderrouter#126]
Hello,
I would like to use border router with KW41Z platform in my project. I followed the installation guide, and everything is running as expected. I can configure and form network etc.

When I try to join the network by device with OT cli firmware using external commissioner (with Thread 1.1 Commissioning App), the process always fails. Client data transmission fails with NoAck error. Client is not able to start handshake with commissioner. CLI device and mobile app logs are attached.
[app_log.txt](https://github.com/openthread/borderrouter/files/1577041/app_log.txt)
[cli_log_info.log](https://github.com/openthread/borderrouter/files/1577042/cli_log_info.log)

I've tried OTBR on two different platforms (Raspberry and C.H.I.P.) and the behaviour was the same.
I used the example drivers from https://github.com/openthread/openthread/tree/master/examples/platforms/kw41z.
- The NCP for border router was built with BORDER_ROUTER=1 JOINER=1 COMMISSIONER=1 TMF_PROXY=1 flags.
- CLI device was built with JOINER=1 COMMISSIONER=1 flags.

Commissioning with two CLI devices without OTBR works well. Can you please give me some advice where should be a problem or what should I do to identify it. I've spent a few days searching and debugging and found no solution. I followed the guide (https://openthread.io/guides/border_router/build), did I miss something? Thank you.

**Comment by indrapanwar** [comment]
Hi,
I am also facing same issue. I followed installation guide and created border router with raspberry pi and KW41z (ncp -ftd). I am able to form network with but not able to join the network with OT CLI firmware on other kw41z device.
Commissioning with two CLI devices  ( one as commissioner and other as joiner ) without OTBR is also not working. 
I downloaded cli -ftd firmware with JOINER =1 COMMISSIONER =1 flags on kw41z. Created network using one board and started commissioner . Joiner boards detects the network and joinable =1 .  Given joiner credential on commissioner board. But the joiner board fails to join the network. I get error "Join failed [Not found]."

Can you give some hints where I am going wrong. Thank you.

**Comment by bukepo** [comment]
@indrapanwar Did you enable `TMF_PROXY=1` flag when compiling NCP? Please note that if you add new flags, you must first delete `build` directory.

**Comment by bukepo** [comment]
@kyberpunk sorry for the late. Did you solve your problem?

**Comment by indrapanwar** [comment]
No i did not enable TMF_PROXY=1 flag. I was doing clean before make with new flags.Thank you. I will try with enabling TMF_PROXY flag.

**Comment by kyberpunk** [comment]
@bukepo No I didn't. There is still the same behaviour. I can connect to OTBR and Thread network with Thread 1.1 Commissioning App, commissioning starts successfully, joiner can find the network but commissioning process always fails. It looks like the joiner device probably can't send any messages to commissioner (error:NoAck in log file). There is the same behaviour on Raspberry Pi 3 and C.H.I.P. devices. I have only KW41Z boards so I didn't try another platform.

**Comment by bukepo** [comment]
@kyberpunk 
The log you posted seems not complete. Could you please modify the log level in https://github.com/openthread/openthread/blob/master/src/core/openthread-core-default-config.h#L559 to generate more detailed log?

Besides, according to the Thread spec, the joiner credential should be at least 6-byte long. Could you please a longer one like `joiner start 123456`?

**Comment by indrapanwar** [comment]
@bukepo 
I am also not able to establish commissioning with 2 cli-ftd device without OTBR. Joiner sees the network. 
On giving command >joiner start 123456 , I do not get any status update on joiner window . 
> state shows "disabled".

**Comment by kyberpunk** [comment]
@bukepo Longer credential didn't help. Here is debug level log file:
CLI joiner device: [log_debg1.log](https://github.com/openthread/borderrouter/files/1635469/log_debg1.log)
Android App: [log_android1.txt](https://github.com/openthread/borderrouter/files/1635471/log_android1.txt)

**Comment by bukepo** [comment]
@kyberpunk I didn't find in your log about `/c/cs`, which sets the joiner information. Could you please post full log from beginning? And if you didn't exactly follow the guide in google.io. Could you please also provide detail steps you did?

**Comment by kyberpunk** [comment]
@bukepo Sorry, but I'm not able to share whole application log while the mobile app shows only last 2000 lines. There is the part with barcode scanning: [barcode_log.txt](https://github.com/openthread/borderrouter/files/1635996/barcode_log.txt)

I followed exactly this guide: https://openthread.io/guides/border_router/external_commissioning. I've used Web GUI for form network.

wpanctl status: 

```
wpan0 => [
        "NCP:State" => "associated"
        "Daemon:Enabled" => true
        "NCP:Version" => "OPENTHREAD/20170716-00343-g38b7d9e-dirty; KW41Z; Dec 19 2017 22:17:25"
        "Daemon:Version" => "0.08.00d (/37260ea; Oct 25 2017 07:21:58)"
        "Config:NCP:DriverName" => "spinel"
        "NCP:HardwareAddress" => [DED4040000000000]
        "NCP:Channel" => 15
        "Network:NodeType" => "leader"
        "Network:Name" => "OpenThreadDemo"
        "Network:XPANID" => 0x1111111122222222
        "Network:PANID" => 0x1234
        "IPv6:MeshLocalAddress" => "fd11:1111:1122:0:1c23:9cfe:560e:63ca"
        "IPv6:MeshLocalPrefix" => "fd11:1111:1122::/64"
        "com.nestlabs.internal:Network:AllowingJoin" => false
]
```

QR Code string:
v=1&&eui=bdaf050000000000&&cc=123456

**Comment by jwhui** [comment]
@indrapanwar, I just tried Thread Commissioning between two KW41Z boards running ot-cli-ftd and it works for me.

1. Get the Joiner's EUI-64
```bash
> eui64                                 
2260070000000000                        
```

2. Setup the Commissioner.
```bash
> panid 0x5656                          
Done                                    
> ifconfig up                           
Done                                    
> thread start                                                           
Done
> commissioner start                                                            
Done                                                                            
> commissioner joiner add 2260070000000000 PSK                                  
Done                                                                            
```

3. Start the Joiner.
```bash
> ifconfig up                           
Done
> joiner start PSK
Done                                                                      
> Join success                                                                  
> panid                                                                         
5656                                                                            
```

Note that crypto acceleration is not enabled by default on the KW41Z, so expect to wait around 30 seconds for the process to complete.

**Comment by kyberpunk** [comment]
@jwhui Did you try also any OTBR device with KW41Z as NCP?

**Comment by jwhui** [comment]
@kyberpunk, I assume you mean with the Thread 1.1 Commissioning App as well.  Unfortunately, I have not directly tested that scenario recently.  However, the failures you are experiencing may be due to https://github.com/openthread/openthread/issues/2176.

**Comment by kyberpunk** [comment]
@jwhui Yes, I mean the use case with the Android app. I've already tried the latest mbedTLS version and mentioned patches and it didn't help.

**Comment by indrapanwar** [comment]
@jwhui : I could join thread network by out-of band commissioning. 
1 ) Downloaded ot-cli-ftd (JOINER =1) on one KW41Z board and other KW41Z board with ot-cli-ftd (COMMISSIONER =1).  Created thread network through commissioner and entered same parameters (networkname, panid, ext panid, channel, masterkey) for joiner.Then on joiner gave command of "ifconfig up" and "thread start". Joiner initially joins as child and later promotes itself to router.
2) Downloaded ot-cli-ftd (COMMISSIONER = 1)  on one KW41Z and other KW41Z board with ot-ncp-ftd(JOINER =1). Created thread network through commissioner . On joiner manually entered network key ("setprop Network:Key xxxxxx...." ) and then join network command (join 1).  
But i am unable to do in-band commissioning. i get error join failed [ResponeTimeOut] or join failed [Security] or i don't get any response.

**Comment by kyberpunk** [comment]
@indrapanwar Did you read solution mentioned in the issue [openthread/openthread#2176](https://github.com/openthread/openthread/issues/2176)? I was facing similar problems with CLI devices, but the latest mbedTLS version and patches in this thread improved the commissioning process slightly for me. I am able to join network in 80% attempts now using CLI firmware.

**Comment by indrapanwar** [comment]
@kyberpunk : Thank you . I will go through the  issue.  I created network by ot-ncp-ftd (TMF=1,BORDERROUTER=1,JOINER=1) and ot-cli-ftd (JOINER=1) could join the network through in-band commissioning. I could ping border router from CLI.

**Comment by kyberpunk** [comment]
@indrapanwar Thank you. So I suppose there could be some mistake on my side. Can you tell me please what HW do you use for CLI and NCP device and for OTBR? Did you follow the [guides](https://openthread.io/guides/border_router/access_point) or have you solved something differently? Have you also tried to form network with web GUI?

**Comment by jwhui** [comment]
@kyberpunk, maybe you are also experiencing https://github.com/openthread/openthread/issues/2081?

**Comment by bukepo** [comment]
@kyberpunk I can only get very limited information from the logs you shared. Did you try using the command line tool *adb* to save android log? I think it will not be limited to only 2000 lines. Besides, can you also provide the *otbr-agent* log.
You may increase the debug level of *otbr-agent* by adding `-d 7` to `OTBR_AGENT_OPTS` in */etc/default/otbr-agent*. And filter logs in syslog file(*/var/log/syslog*) by grep *otbr-agent*.

**Comment by indrapanwar** [comment]
@kyberpunk I used Raspberry Pi 3B and  KW41Z for OTBR. Programmed KW41Z with ot-cli-ncp and with configuration TMF=1, BORDERROUTER=1, JOINER=1. I followed the guide. Created thread network manually. Other board KW41Z is programmed with ot-cli-ftd , JOINER=1. Entered the same network parameters for CLI. Initiallty CLI joined as child but later upgraded itself to router and was able to ping border router.

**Comment by kyberpunk** [comment]
@indrapanwar Are you sure you have compiled the NCP firmware with JOINER flag? There is COMMISSIONER flag in the guide instead.

**Comment by indrapanwar** [comment]
@kyberpunk yes . I used in-band commissioning. I also tried with two CLI (JOINER=1). Created thread network with one CLI and provided same network credentials to other CLI. The later joined as child initially and later promoted to router. If leader ( with which thread network was created) went down then router took the role of leader.

**Comment by kyberpunk** [comment]
@bukepo Sorry for the delay. Here are full logs you have requested.
[log_android_app.txt](https://github.com/openthread/borderrouter/files/1664998/log_android_app.txt)
[log_otbr_agent.txt](https://github.com/openthread/borderrouter/files/1664999/log_otbr_agent.txt)
[log_cli.log](https://github.com/openthread/borderrouter/files/1665000/log_cli.log)

**Comment by kyberpunk** [comment]
@bukepo Did you make any conclusions based on log files? Can I do something else?

**Comment by bukepo** [comment]
Hi @kyberpunk, sorry for the late. From the logs you shared, it seems the DTLS requests may not be successfully sent by the joiner. As in the log_cli.log, I cannot find log showing sending the DTLS client hello. You may find something like this which shows sending Discovery Request on channel 25.
```
[25/01/18 - 16:23:26:246] [DEBG]-MAC-----: Finishing operation "TransmitData"^M
[25/01/18 - 16:23:26:248]

[25/01/18 - 16:23:26:248] [DEBG]-MAC-----: Idle mode: Radio receiving on channel 25^M
[25/01/18 - 16:23:26:250]

[25/01/18 - 16:23:26:250] PuTTY[DEBG]-MAC-----: Request to start operation "TransmitData"^M
[25/01/18 - 16:23:26:504]

[25/01/18 - 16:23:26:504] [DEBG]-MAC-----: Starting operation "TransmitData"^M
[25/01/18 - 16:23:26:509]

[25/01/18 - 16:23:26:509] ==============================[TX len=037]===============================^M
[25/01/18 - 16:23:26:516]

[25/01/18 - 16:23:26:516] | 01 D8 79 FF FF FF FF E3 | D3 3D A9 FC 7F 85 53 9A | ^AXy......=.|.^E..^M
[25/01/18 - 16:23:26:538]

[25/01/18 - 16:23:26:538] | 83 7F 3B 02 F0 4D 4C 4D | 4C A8 3E FF 10 1A 04 80 | ...^BpMLML.....^D.^M
[25/01/18 - 16:23:26:542]

[25/01/18 - 16:23:26:542] | 02 28 00 A0 AF .. .. .. | .. .. .. .. .. .. .. .. | ^B...............^M
[25/01/18 - 16:23:26:544]

[25/01/18 - 16:23:26:545] ------------------------------------------------------------------------^M
```
I also checked log_otbr_agent.txt, it shows no Relay Receive(URI: c/rx) were received by border agent. This also indicate the DTLS client hello might not be transmitted by joiner.

Did you changed the source code of OpenThread? Could you possibly somehow make sure the packets were transmitted? For example, try using a sniffer to capture packets. Or disable MESH layer log by define `OPENTHREAD_CONFIG_LOG_MLE=0`, it seems some logs were overwritten by other logs.

**Comment by kyberpunk** [comment]
@bukepo I've spent some hours by JTAG debugging. Network discovery and commissioner steering data reception works correctly. But client hello transmition and all retransmit attempts fail with no acknowledgement error (as you can see in the log). Frame is never received by NCP device and no client hello message was captured by sniffer. I've tried 2 different border router HW platforms.
[log.log](https://github.com/openthread/borderrouter/files/1764463/log.log)

I've tried latest sources without any changes and behaviour is still the same. If I use only 2 CLI devices commissioning works well. Could be the problem in the frame destination address or something?

**Comment by kyberpunk** [comment]
@bukepo I'm sorry, for some reason client device datagrams were not received by NCP. I've tried another attempt and client hello was sent correctly. Commissioner probably got message, processed J-PAKE info and sent message to the joiner. After that I'm not sure what happened (17:36:03.681 in android app log).

Here are new logs:
[cli_log.log](https://github.com/openthread/borderrouter/files/1768980/cli_log.log)
[otbr_log.log](https://github.com/openthread/borderrouter/files/1768981/otbr_log.log)
[cli_log.log](https://github.com/openthread/borderrouter/files/1768983/cli_log.log)
And onother CLI log with OPENTHREAD_CONFIG_LOG_MLE=0:
[cli_log.log](https://github.com/openthread/borderrouter/files/1768985/cli_log.log)

I've spent some hours debugging commissioning process between two CLI devices with JTAG. There is obviously issue with DTLS retransmissioning mentioned in [openthread/openthread#2176](https://github.com/openthread/openthread/issues/2176). When I raised DTLS retransmission timeouts, joiner always suceeded. So it is probably caused by slow platform.

About external commissioning I am really clueless. Could it be related to this issue or to [openthread/openthread#2081](https://github.com/openthread/openthread/issues/2081)? Can I solve it somehow? 

I can use NXP Thread platform specific sources for my project (I've tried and it works well) but I would like rather use OpenThread for portability and other reasons.

**Comment by jwhui** [comment]
@kyberpunk, are you using the kw41z platform?  There are known issues specific to kw41z example drivers that we're currently looking into.  See thread [here](https://groups.google.com/d/msg/openthread-users/UqXO4qKzVb4/I6Skqfc6BAAJ).

**Comment by kyberpunk** [comment]
@jwhui Yes I am using KW41Z and I am experincing the same issue described in your link.

But there are two problems I've found. In the last log posted by C. Eldridge the client hello message is never sent correctly because of NoAck error. It happened also in my case, but I solved it by leaving network (sudo wpanctl leave on OTBR) and forming it again with web GUI. After that messages are sent correctly but the commissioning process fails with the same result. See my last logs for details.

Is there any way I can help somehow?

**Comment by jwhui** [comment]
@kyberpunk, the CLI logs show that the KW41Z NCP is not properly receiving IEEE 802.15.4 ACKs when sending messages to the Joiner.  This is evident in the multiple prints of "Dropping (reassembly queue)".  The NCP is trying to send the same message multiple times to the Joiner, but failing to progress because it is not receiving the ACK.

```
[27/02/18 - 21:25:19:840] | [INFO]-MAC-----: Dropping (reassembly queue) IPv6 UDP msg, len:671, chksum:2030, sec:no, error:ReassemblyTimeout, prio:low, rss
```

We have someone from NXP who will look into this issue.

**Comment by kyberpunk** [comment]
Thank you for the information. Please let me know about the updates.

**Comment by kyberpunk** [comment]
@jwhui Thank you for the information. Please let me know about the updates.

**Comment by jwhui** [comment]
Resolved by https://github.com/openthread/openthread/pull/2753.

**Comment by kyberpunk** [comment]
I can confirm It works now. Thanks.
