### ISSUE TITLE
how is wpantund linked into the borderrouter

### ISSUE THREAD

**Issue by thcu-gp** [openthread/borderrouter#132]
* There is a wpantund located in /thirdparty/wpantund/rep
* script/setup clones wpantund into ._build/wpantund

So why would setup clone wpantund if there is a copy available in the repo already - or - why having it in the repo if the setup script is going to clone it anyways.

What is the preferred approach here?

Besides cloning within a git repo is not very useful, since all git  functionality is lost for the inner clone. Better to make it a git submodule or clone it outside the borderrouter repo

**Comment by bukepo** [comment]
@thcu-gp, wpantund located in third_party is an work version for borderrouter and is only partly compiled into a simple library for accessing wpantund d-bus service. While `script/setup` pulls the latest wpantund code, which is supposed to work better with the latest openthread and provide d-bus service to talk to openthread.

For submodule, this project just follows openthread's pattern, which makes this project can compile without having to pull other projects.
