### ISSUE TITLE
Dnsmasq service fails to start - Address already in use

### ISSUE THREAD

**Issue by ubx-caloca** [openthread/borderrouter#134]
I downloaded the OTHBR code from the latest commit (07ea4a54a5ee4105475627fa23d65d2cdda9ec14) and followed all the steps exactly as described in the OTBR setup guide (https://openthread.io/guides/border_router) in a Raspberry Pi 3 with Raspbian Lite 2017-11-29 . However I'am getting an error when booting Raspbian :

.....
0;32m  OK  0m Started OpenBSD Secure Shell server.
0;1;31mFAILED 0m Failed to start dnsmasq - A lightweight DHCP and caching DNS server.
See 'systemctl status dnsmasq.service' for details.
0;32m  OK  0m Reached target Host and Network Name Lookups.
.....

The status of the dnsmasq service (got from executing "sudo systemctl status dnsmasq") is the following 
....
dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled; vendor preset: enabled)
   Active: failed Result: exit-code since Fri 2018-02-02 22:17:15 UTC; 2min 52s ago
  Process: 497 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=2)
  Process: 467 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=0/SUCCESS)

Feb 02 22:17:14 raspberrypi systemd 1: Starting dnsmasq - A lightweight DHCP and caching DNS server...
Feb 02 22:17:14 raspberrypi dnsmasq 467: dnsmasq: syntax check OK.
Feb 02 22:17:15 raspberrypi systemd 1: dnsmasq.service: Control process exited, code=exited status=2
Feb 02 22:17:15 raspberrypi dnsmasq 497: dnsmasq: failed to create listening socket for 192.168.1.2: Address already in use
Feb 02 22:17:15 raspberrypi systemd 1: Failed to start dnsmasq - A lightweight DHCP and caching DNS server.
Feb 02 22:17:15 raspberrypi systemd 1: dnsmasq.service: Unit entered failed state.
Feb 02 22:17:15 raspberrypi systemd 1: dnsmasq.service: Failed with result 'exit-code'
.....

Searching the web it seems that bind9 and dnsmasq are not playing well with each other. When a ran the "sudo netstat -anlp | grep -w LISTEN" it seems that bind9 is already listening to the endpoint 192.168.1.2:53 as shown is the previous netstat command output:
.....
tcp        0      0 192.168.255.1:53        0.0.0.0:*               LISTEN      461/named           
tcp        0      0 192.168.86.51:53        0.0.0.0:*               LISTEN      461/named           
tcp        0      0 192.168.1.2:53          0.0.0.0:*               LISTEN      461/named           
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      461/named           
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      480/sshd            
tcp        0      0 127.0.0.1:953           0.0.0.0:*               LISTEN      461/named           
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      463/otbr-web        
tcp6       0      0 :::53                   :::*                    LISTEN      461/named           
tcp6       0      0 :::22                   :::*                    LISTEN      480/sshd            
tcp6       0      0 ::1:953                 :::*                    LISTEN      461/named   
....

If I stop the bind9 and dnsmasq services, then start dnsmasq followed by bind9, both start without errors. Looking at the OTBR bootstap and setup scripts it seems that bind9 is installed first in the bootstap script then dnsmasq is installed in the setup script and somehow bind9 always starts first at boot.

**Comment by bukepo** [comment]
@prfi It seems there's some conflict between dnsmasq and bind9. Shall we disable the DNS server of dnsmasq?

**Comment by ubx-caloca** [comment]
I was using Raspbian Stretch 2017-11-29.  I will try again with version 2017-11-29 and the latest commit and with the newer 2018-03-13.

**Comment by ubx-caloca** [comment]
I installed the OTBR 3 times from scratch. Two times using Stretch 2017-11-29, the first time I didn't get the issue, the second time the issue appears. Then install one time using Stretch 2018-03-13 and the issue was there. I still don't know why sometimes it works and sometimes it doesn't.

My solution to fix the issue is to modify the bind9.service to force bind9 to start only after dnsmasq. The modified bind9.service results in this:


```
[Unit]
Description=BIND Domain Name Server
Documentation=man:named(8)
After=network.target dnsmasq.service
Wants=nss-lookup.target
Before=nss-lookup.target

[Service]
EnvironmentFile=/etc/default/bind9
ExecStart=/usr/sbin/named -f $OPTIONS
ExecReload=/usr/sbin/rndc reload
ExecStop=/usr/sbin/rndc stop

[Install]
WantedBy=multi-user.target
```

**Comment by leonsteenkamp** [comment]
I think I've run into a the same problem. 

Fresh Raspbian Stretch (Lite) 2018-04-18 install following the Get Started guide.  BorderRouter code is the latest commit - a9cc157. Raspian is updated and with rpi-update.

This causes the Web GUI not to load and no Internet on wifi access point. Stopping dnsmasq and bind9 then starting dnsmasq and then bind9 seems to resolve the issue.

```$ cat /proc/cpuinfo
Revision	: a02082
```
```cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by ubx-caloca** [comment]
I've always get this issue. My fix is to modify the
/lib/systemd/system/bind9.service file and modify the "After" line to this
"After=network.target dnsmasq.service"

**Comment by yz101-osrm** [comment]
I've run into the same dnsmasq issue here. @ubx-caloca 's modification helps resolve it. Thanks.

**Comment by Vyrastas** [comment]
Ran into the same issue, the fix from @ubx-caloca worked for me as well.  bind9 needs to start after dnsmasq when the system boots.

**Comment by bukepo** [comment]
The guide has been updated.
