### ISSUE TITLE
Use KW41Z as NCP

### ISSUE THREAD

**Issue by ekarlso** [openthread/borderrouter#135]
Hi, is the correct way to use KW41Z as a NCP like this when building the firmware:
make -f examples/Makefile-kw41z TMF_PROXY=1 BORDER_ROUTER=1 COMMISSIONER=1 USB=1

I then flash it by copying to 
sudo cp output/kw41z/bin/ot-ncp-ftd /mnt/

Which is the flash directory where I read it should pickup the flash file from.

But then wpantund says
Feb 25 19:17:14 raspberrypi wpantund[2391]:         BUILD_VERSION = 6e39f94
Feb 25 19:17:14 raspberrypi wpantund[2391]: wpantund[2391]:         BUILD_VERSION = 6e39f94
Feb 25 19:17:14 raspberrypi wpantund[2391]: wpantund[2391]: Configuration file "/etc/wpantund.conf" read.
Feb 25 19:17:14 raspberrypi wpantund[2391]: Configuration file "/etc/wpantund.conf" read.
Feb 25 19:17:14 raspberrypi NetworkManager[343]: <info>  [1519586234.8082] manager: (wpan0): new Tun device (/org/freedesktop/NetworkManager/Devices/5)
Feb 25 19:17:14 raspberrypi wpantund[2391]: wpantund[2391]: Ready. Using DBUS bus ":1.31"
Feb 25 19:17:14 raspberrypi wpantund[2391]: wpantund[2391]: Running as root without dropping privileges!
Feb 25 19:17:14 raspberrypi wpantund[2391]: Ready. Using DBUS bus ":1.31"
Feb 25 19:17:14 raspberrypi wpantund[2391]: Running as root without dropping privileges!
Feb 25 19:17:14 raspberrypi NetworkManager[343]: <info>  [1519586234.8488] devices added (path: /sys/devices/virtual/net/wpan0, iface: wpan0)
Feb 25 19:17:14 raspberrypi NetworkManager[343]: <info>  [1519586234.8490] device added (path: /sys/devices/virtual/net/wpan0, iface: wpan0): no ifupdown configuration found.
Feb 25 19:17:19 raspberrypi wpantund[2391]: wpantund[2391]: SpinelNCPInstance-Protothreads.cpp:412: Requirement Failed (IS_EVENT_FROM_NCP(event) && GetInstance(this)->mInboundHeader == mLastHeader)
Feb 25 19:17:19 raspberrypi wpantund[2391]: SpinelNCPInstance-Protothreads.cpp:412: Requirement Failed (IS_EVENT_FROM_NCP(event) && GetInstance(this)->mInboundHeader == mLastHeader)
Feb 25 19:17:20 raspberrypi wpantund[2391]: wpantund[2391]: Resetting and trying again... (retry 1)
Feb 25 19:17:20 raspberrypi wpantund[2391]: Resetting and trying again... (retry 1)
Feb 25 19:17:25 raspberrypi wpantund[2391]: wpantund[2391]: SpinelNCPInstance-Protothreads.cpp:402: Requirement Failed (event == EVENT_NCP_RESET)
Feb 25 19:17:25 raspberrypi wpantund[2391]: SpinelNCPInstance-Protothreads.cpp:402: Requirement Failed (event == EVENT_NCP_RESET)

**Comment by bukepo** [comment]
I think you need convert the *ot-cli-ftd* to *ot-cli-ftd.bin* according to https://github.com/openthread/openthread/tree/master/examples/platforms/kw41z
