### ISSUE TITLE
Error getting wpan to work.

### ISSUE THREAD

**Issue by ekarlso** [openthread/borderrouter#138]
Hi, I am unable to start the otbr:
```
Mar 17 20:30:20 raspberrypi sudo[15615]: pam_unix(sudo:session): session closed for user root
Mar 17 20:30:20 raspberrypi wpantund[15629]: wpantund[15629]: Starting wpantund 0.08.00d (Mar 17 2018 18:18:34) . . .
Mar 17 20:30:20 raspberrypi wpantund[15629]: wpantund[15629]:         BUILD_VERSION = ed49abb
Mar 17 20:30:20 raspberrypi wpantund[15629]: Starting wpantund 0.08.00d (Mar 17 2018 18:18:34) . . .
Mar 17 20:30:20 raspberrypi wpantund[15629]: wpantund[15629]: Configuration file "/etc/wpantund.conf" read.
Mar 17 20:30:20 raspberrypi wpantund[15629]:         BUILD_VERSION = ed49abb
Mar 17 20:30:20 raspberrypi wpantund[15629]: Configuration file "/etc/wpantund.conf" read.
Mar 17 20:30:20 raspberrypi NetworkManager[4635]: <info>  [1521318620.7726] manager: (wpan0): new Tun device (/org/freedesktop/NetworkManager/Devices/6)
Mar 17 20:30:20 raspberrypi wpantund[15629]: wpantund[15629]: Ready. Using DBUS bus ":1.70"
Mar 17 20:30:20 raspberrypi wpantund[15629]: wpantund[15629]: Running as root without dropping privileges!
Mar 17 20:30:20 raspberrypi wpantund[15629]: Ready. Using DBUS bus ":1.70"
Mar 17 20:30:20 raspberrypi wpantund[15629]: Running as root without dropping privileges!
Mar 17 20:30:20 raspberrypi NetworkManager[4635]: <info>  [1521318620.8114] devices added (path: /sys/devices/virtual/net/wpan0, iface: wpan0)
Mar 17 20:30:20 raspberrypi NetworkManager[4635]: <info>  [1521318620.8116] device added (path: /sys/devices/virtual/net/wpan0, iface: wpan0): no ifupdown configuration found.
Mar 17 20:30:20 raspberrypi wpantund[15629]: wpantund[15629]: State change: "uninitialized" -> "offline"
Mar 17 20:30:20 raspberrypi wpantund[15629]: State change: "uninitialized" -> "offline"
Mar 17 20:30:20 raspberrypi wpantund[15629]: NCP is running "OPENTHREAD/20170716-00331-g9428a2fe-dirty; NRF52840; Dec  7 2017 16:14:22"
Mar 17 20:30:20 raspberrypi wpantund[15629]: wpantund[15629]: NCP is running "OPENTHREAD/20170716-00331-g9428a2fe-dirty; NRF52840; Dec  7 2017 16:14:22"
Mar 17 20:30:20 raspberrypi wpantund[15629]: wpantund[15629]: Driver is running "0.08.00d (/ed49abb; Mar 17 2018 18:18:34)"
Mar 17 20:30:20 raspberrypi wpantund[15629]: Driver is running "0.08.00d (/ed49abb; Mar 17 2018 18:18:34)"
Mar 17 20:30:20 raspberrypi wpantund[15629]: wpantund[15629]: Network is not joinable
Mar 17 20:30:20 raspberrypi wpantund[15629]: Network is not joinable
Mar 17 20:30:20 raspberrypi wpantund[15629]: wpantund[15629]: Resetting interface(s). . .
Mar 17 20:30:20 raspberrypi wpantund[15629]: Resetting interface(s). . .
Mar 17 20:30:20 raspberrypi wpantund[15629]: wpantund[15629]: ../util/netif-mgmt.c:530: Requirement Failed ((ret) == 0)
Mar 17 20:30:20 raspberrypi wpantund[15629]: wpantund[15629]: Finished initializing NCP
Mar 17 20:30:20 raspberrypi wpantund[15629]: ../util/netif-mgmt.c:530: Requirement Failed ((ret) == 0)
Mar 17 20:30:20 raspberrypi wpantund[15629]: ../util/netif-mgmt.c:530: Requirement Failed ((ret) == 0)
Mar 17 20:30:20 raspberrypi wpantund[15629]: ../util/netif-mgmt.c:530: Requirement Failed ((ret) == 0)
Mar 17 20:30:20 raspberrypi wpantund[15629]: ../util/netif-mgmt.c:530: Requirement Failed ((ret) == 0)
Mar 17 20:30:20 raspberrypi wpantund[15629]: ../util/netif-mgmt.c:530: Requirement Failed ((ret) == 0)
Mar 17 20:30:20 raspberrypi wpantund[15629]: Finished initializing NCP
Mar 17 20:30:22 raspberrypi sudo[15640]:       pi : TTY=pts/1 ; PWD=/home/p

wpan0 => [
        "NCP:State" => "offline"
        "Daemon:Enabled" => true
        "NCP:Version" => "OPENTHREAD/20170716-00331-g9428a2fe-dirty; NRF52840; Dec  7 2017 16:14:22"
        "Daemon:Version" => "0.08.00d (/ed49abb; Mar 17 2018 18:18:34)"
        "Config:NCP:DriverName" => "spinel"
        "NCP:HardwareAddress" => [9EB122C14D1FB342]
]
```

**Comment by jwhui** [comment]
It appears that wpantund did start properly.  You just need to form a Thread network.

BTW, there is [newer firmware available](https://openthread.io/guides/ncp/firmware).  You may want to reflash your NCP with the newer version.

**Comment by NickNamerr** [comment]
wpantund[3251]: State change: "uninitialized" -> "offline"
wpantund[3251]: NCP is running "OPENTHREAD/20170716-00680-gb833373-dirty; EFR32; Jun 21 2018 11:59:49"
wpantund[3251]: Driver is running "0.08.00d (0.07.01-223-g50adabd; Jun 21 2018 12:50:41)"
wpantund[3251]: Network is not joinable
wpantund[3251]: Unsuccessful in restoring property "NCP:CCAThreshold" on NCP: "STATUS_PROP_NOT_FOUND" (13)
wpantund[3251]: Resetting interface(s). . .
wpantund[3251]: ../util/netif-mgmt.c:530: Requirement Failed ((ret) == 0)
wpantund[3251]: ../util/netif-mgmt.c:530: Requirement Failed ((ret) == 0)
wpantund[3251]: ../util/netif-mgmt.c:530: Requirement Failed ((ret) == 0)
wpantund[3251]: ../util/netif-mgmt.c:530: Requirement Failed ((ret) == 0)
wpantund[3251]: ../util/netif-mgmt.c:530: Requirement Failed ((ret) == 0)
wpantund[3251]: Finished initializing NCP
wpantund[3251]: State change: "offline" -> "associating"
wpantund[3251]: State change: "associating" -> "associated"
wpantund[3251]: ../util/netif-mgmt.c:119: Requirement Failed (Operation not permitted)
wpantund[3251]: ../util/TunnelIPv6Interface.cpp:391: Requirement Failed (ret == 0)
wpantund[3251]: Node type change: "unknown" -> "end-device"


wpanctl:wpan0> status
wpan0 => [
        "NCP:State" => "associated"
        "Daemon:Enabled" => true
        "NCP:Version" => "OPENTHREAD/20170716-00680-gb833373-dirty; EFR32; Jun 21 2018 11:59:49"
        "Daemon:Version" => "0.08.00d (0.07.01-223-g50adabd; Jun 21 2018 12:50:41)"
        "Config:NCP:DriverName" => "spinel"
        "NCP:HardwareAddress" => [000B57FFFEA77ECE]
        "NCP:Channel" => 11
        "Network:NodeType" => "end-device"
        "Network:Name" => "OpenThreadDemo"
        "Network:XPANID" => 0x1111111122222222
        "Network:PANID" => 0x1234
        "IPv6:MeshLocalAddress" => "fd11:1111:1122:0:e163:78f7:cf7:dd5b"
        "IPv6:MeshLocalPrefix" => "fd11:1111:1122::/64"
        "com.nestlabs.internal:Network:AllowingJoin" => false
]


ifconfig wpan0
wpan0: flags=4240<POINTOPOINT,NOARP,MULTICAST>  mtu 1280
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 500  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by jwhui** [comment]
@NickNamerr, as noted above, please trying using a newer firmware build (e.g. HEAD of master).  If you are using EFR32, you will need to build that image from source.

**Comment by NickNamerr** [comment]
i am using newer firmware:
"NCP:Version" => "OPENTHREAD/20170716-00680-gb833373-dirty; EFR32; Jun 21 2018 11:59:49"
and latest wpantund version:
"Daemon:Version" => "0.08.00d (0.07.01-223-g50adabd; Jun 21 2018 12:50:41)"

**Comment by jwhui** [comment]
@NickNamerr the NCP version indicates otherwise: "20170716".  What commit id are you using?

**Comment by NickNamerr** [comment]
@jwhui 
[nick openthread]$ git log -1 | grep ^commit | cut -d " " -f 2
b8333732fa543b32ecf10cd8eec2f8988821436e

**Comment by jwhui** [comment]
Can you provide the info necessary to reproduce, including your EFR32 board info, build steps, etc?

**Comment by NickNamerr** [comment]
I am running wpantund on RHEL7.5
EFR32 board is BRD4168A with chipset EFR32MG13P732F512GM48. 

Changes in attached file.
[diff.txt](https://github.com/openthread/borderrouter/files/2122449/diff.txt)

arm-none-eabi-gcc -v
Using built-in specs.
COLLECT_GCC=arm-none-eabi-gcc
COLLECT_LTO_WRAPPER=/home/admin/gnu/gcc-arm-none-eabi-4_9-2015q3/bin/../lib/gcc/arm-none-eabi/4.9.3/lto-wrapper
Target: arm-none-eabi
Configured with: /home/build/work/GCC-4-9-build/src/gcc/configure --target=arm-none-eabi --prefix=/home/build/work/GCC-4-9-build/install-native --libexecdir=/home/build/work/GCC-4-9-build/install-native/lib --infodir=/home/build/work/GCC-4-9-build/install-native/share/doc/gcc-arm-none-eabi/info --mandir=/home/build/work/GCC-4-9-build/install-native/share/doc/gcc-arm-none-eabi/man --htmldir=/home/build/work/GCC-4-9-build/install-native/share/doc/gcc-arm-none-eabi/html --pdfdir=/home/build/work/GCC-4-9-build/install-native/share/doc/gcc-arm-none-eabi/pdf --enable-languages=c,c++ --enable-plugins --disable-decimal-float --disable-libffi --disable-libgomp --disable-libmudflap --disable-libquadmath --disable-libssp --disable-libstdcxx-pch --disable-nls --disable-shared --disable-threads --disable-tls --with-gnu-as --with-gnu-ld --with-newlib --with-headers=yes --with-python-dir=share/gcc-arm-none-eabi --with-sysroot=/home/build/work/GCC-4-9-build/install-native/arm-none-eabi --build=i686-linux-gnu --host=i686-linux-gnu --with-gmp=/home/build/work/GCC-4-9-build/build-native/host-libs/usr --with-mpfr=/home/build/work/GCC-4-9-build/build-native/host-libs/usr --with-mpc=/home/build/work/GCC-4-9-build/build-native/host-libs/usr --with-isl=/home/build/work/GCC-4-9-build/build-native/host-libs/usr --with-cloog=/home/build/work/GCC-4-9-build/build-native/host-libs/usr --with-libelf=/home/build/work/GCC-4-9-build/build-native/host-libs/usr --with-host-libstdcxx='-static-libgcc -Wl,-Bstatic,-lstdc++,-Bdynamic -lm' --with-pkgversion='GNU Tools for ARM Embedded Processors' --with-multilib-list=armv6-m,armv7-m,armv7e-m,cortex-m7,armv7-r
Thread model: single
gcc version 4.9.3 20150529 (release) [ARM/embedded-4_9-branch revision 227977] (GNU Tools for ARM Embedded Processors)





file compile-efr32 :
#!/bin/bash

make -f examples/Makefile-efr32 COMMISSIONER=1 TMF_PROXY=1 BORDER_ROUTER=1 BOARD=BRD4168A $*

for j in cli ncp
do

for i in ftd mtd
        do arm-none-eabi-objcopy -O ihex output/efr32/bin/ot-$j-$i output/efr32/bin/ot-$j-$i.hex ;
        arm-none-eabi-objcopy -O binary output/efr32/bin/ot-$j-$i output/efr32/bin/ot-$j-$i.bin
        echo $j-$i;
done
done

**Comment by NickNamerr** [comment]
Just tried to do on another PC with Ubuntu OS:
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.10
DISTRIB_CODENAME=artful
DISTRIB_DESCRIPTION="Ubuntu 17.10"


Same result.

Maybe it will help:
syslog:
Jun 21 15:08:36 ubuntu-pc NetworkManager[810]: <info>  [1529564916.7369] manager: (wpan0): new Tun device (/org/freedesktop/NetworkManager/Devices/7)
Jun 21 15:08:36 ubuntu-pc NetworkManager[810]: <info>  [1529564916.7467] devices added (path: /sys/devices/virtual/net/wpan0, iface: wpan0)
Jun 21 15:08:36 ubuntu-pc NetworkManager[810]: <info>  [1529564916.7468] device added (path: /sys/devices/virtual/net/wpan0, iface: wpan0): no ifupdown configuration found.


ifconfig
enp3s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.147  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::6ebc:820a:dc61:dc83  prefixlen 64  scopeid 0x20<link>
        ether 88:d7:f6:7d:fb:18  txqueuelen 1000  (Ethernet)
        RX packets 4753375  bytes 506747981 (506.7 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 101874  bytes 9304774 (9.3 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 8146  bytes 793026 (793.0 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 8146  bytes 793026 (793.0 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


wpan0 did not bring up.

**Comment by NickNamerr** [comment]
Used https://openthread.io/guides/border-router/build to build from scratch.

After i followed https://fedoraproject.org/wiki/EPEL and install all necessary software manually (avahi-client and libdaemon, libdaemon in repo but there no libdaemon.pc for pkg-config checks.), manually run "cd borderrouter/third_party/mbedtls/; make install" because of otbr-web.service won't start , libmbedtls.so.0 was not installed.

Webadmin chapters "join" and "status" do not show anything.
