### ISSUE TITLE
How to ping external network

### ISSUE THREAD

**Issue by flywangnwu** [openthread/borderrouter#142]
I run ubuntu 16.04 in my host, So i check ifconfig, then find enp0s3 and wpan0 network device. I think enp0s3 should be real device and wpan0 is a virtual device.
In root account, I can ping child device from host "wpan0" successfully and ping host 'wpan0' from child cli command successfully.
In host side >> ping6 -I wpan0 CHILD_ADDR
or
In child side >> ping WPAN0_ADDR

But I can not use host "enp0s3" 

Do I need to make a bridge between wpan0 and enp0s3 ?

**Comment by jwhui** [comment]
Answered on [openthread-users](https://groups.google.com/d/msg/openthread-users/ggHmrdsugoY/FgLKAn-4AQAJ):

> For Thread to communicate with external IP networks, you need to configure a default route.
> 
> A simple example is:
> 
>     $ sudo wpanctl -I wpan0 config-gateway -d fd00:1234::
> 
> where `fd00:1234::` is the global prefix you want to configure and `-d` indicates to advertise a default route.

**Comment by flywangnwu** [comment]
jwhui, thank you for your response. 
Is the wpanctl configured automatic if i form a network through WED UI?

I have fixed the issue, but I don't known the reason.
After I configured the prefix to prefix 2018:db8:1:ffff::/96 in tayga configuration, I can ping HOST successful. But it is not OK if I set prefix to well-knwon (64:ff9b).

**Comment by jwhui** [comment]
Yes, the prefix and default route can be configured through the web UI.

What is the IPv4 address of your host?  Note that the Well-Known Prefix 64:ff9b::/96 cannot be used to connect with private IPv4 addresses (10.x.x.x, 192.168.x.x, etc).

**Comment by akansal1** [comment]
@jwhui how can I connect to private IPV4 addresses, I have opened a similar issue in openthread  [#2823](https://github.com/openthread/openthread/issues/2823)

**Comment by LuDuda** [comment]
Hello @akansal1,

I believe the easiest solution is to change NAT64 prefix in /etc/tayga.conf to be different than 64:ff9b::/96 and use the different one.

Similar issue, with more details [here](https://devzone.nordicsemi.com/f/nordic-q-a/34902/unable-to-ping-from-thread-cli-example-to-my-pc-on-ipv4-network).

**Comment by akansal1** [comment]
@LuDuda  thanks you solution work partially for me, I am now able to ping to local networks but I am still not able to resolve 127.0.0.1 or 0.0.0.0 via tayga

**Comment by jwhui** [comment]
@akansal1, you should have your server bind to a private or public IP address.
- 127.0.0.1 is the loopback address and typically used to receive packets generated by the host itself.
- 0.0.0.0 is generally viewed as the "unspecified address"
