### ISSUE TITLE
How to change network interface name used by otbr-web?

### ISSUE THREAD

**Issue by antonsviridenko** [openthread/borderrouter#144]
`border router web started on wpan0`

I need to change interface name from "wpan0" to something other, where is this configuration can be changed? I have borderrouter installed on beaglebone black

**Comment by jwhui** [comment]
In `/etc/wpantund.conf` you can specify the `Config:TUN:InterfaceNam` value to something other than `wpan0`.

At the same time, there are a few places in the borderrouter repo where `wpan0` is hardcoded - you will need to replace those as well.  We'll find a better way to make it easier to change this configuration.
