### ISSUE TITLE
PICO-PI-IMX7 as border router

### ISSUE THREAD

**Issue by GizMo94** [openthread/borderrouter#145]
Hello ! 

I'm currently working on a PICO-PI-IMX7 and I am wondering if it's possible to use it as a border router ? 

If yes, what is the best way to start ?

Thank you,

**Comment by jwhui** [comment]
What OS are you running on the PICO-PI-IMX7?

**Comment by GizMo94** [comment]
I'm running with Android Things

**Comment by jwhui** [comment]
Android Things does not currently support Thread Border Routing.  However, it is on the backlog.

**Comment by GizMo94** [comment]
Which OS do you advise, in order to do the Border Router on the PICO ?

**Comment by jwhui** [comment]
Currently, OTBR is commonly run on Raspbian and Ubuntu.
