### ISSUE TITLE
CC2650 LAUNCHXL as NCP

### ISSUE THREAD

**Issue by leonsteenkamp** [openthread/borderrouter#149]
Hi,
Is it possible to use a Raspberry Pi 3B with a CC2650 LAUNCHXL a border router? I am running into some issues and I thought I'd start with the basic questions.

Following the guide its looks like I can compile the NCP example for the device that gives me ot-ncp-mtd binary. But I cannot form a network using the Web GUI and when I use the command line method I get stuck at. 

```sudo wpanctl config-gateway -d "fd11:22::"
Using prefix "fd11:22::"
config-gateway failed with error 16. PropertyNotFound
```
I can also not form a network
```sudo wpanctl form "wpantund-testnet"
Forming WPAN "wpantund-testnet" as node type "router"
form: error: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```
But I do get the expected status
```sudo wpanctl status
wpan0 => [
	"NCP:State" => "offline"
	"Daemon:Enabled" => true
	"NCP:Version" => "OPENTHREAD/20170716-00650-g631557e8-dirty; CC2650; Jun  9 2018 17:01:11"
	"Daemon:Version" => "0.08.00d (/198ffcb; Jun 13 2018 22:36:39)"
	"Config:NCP:DriverName" => "spinel"
	"NCP:HardwareAddress" => [00124B000F28D501]
]
```
I am using version 7.2.1 20170904 (release) of the arm toolchain and was thinking of giving an older version a try like suggested on the device example page.

**Comment by bukepo** [comment]
@leonsteenkamp mtd cannot form new network because it cannot act as router.

**Comment by leonsteenkamp** [comment]
Hi @bukepo, thanks for the clarification.
