### ISSUE TITLE
Android Things Support

### ISSUE THREAD

**Issue by jamesblasco** [openthread/borderrouter#15]
It would be a great oportunity to support  borderrouter project in a raspberry pi builded with Android Things image. Android Things is a platform based on Linux kernel that makes easy to create iot devices which can communicate easily with each other  and with other platforms such as android phones, windows or ios

**Comment by jwhui** [comment]
Thanks for this request!  As FYI, this border router project initially targets Linux platforms and has been demonstrated on a Raspberry Pi 3 running Raspbian Jesse Lite.  We plan on supporting more platforms, and Android Things would be a great target.  We'll keep this on the backlog.

**Comment by vinvinodk** [comment]
Great..! Happy to see this [press-release](https://android-developers.googleblog.com/2017/12/lowpan-on-android-things.html). A big door opened for me.

**Comment by beriberikix** [comment]
See also androidthings/sample-lowpan#1
