### ISSUE TITLE
CC2652 NCP:State uninitialized

### ISSUE THREAD

**Issue by yz101-osrm** [openthread/borderrouter#155]
I use a Raspberry Pi 3B with a CC2652 as a border router. I am running to some issues of NCP state. 

`$sudo wpanctl status`

wpan0 shows 

	"NCP:State" => "uninitialized:fault"
	"Daemon:Enabled" => true
	"NCP:Version" => ""
	"Daemon:Version" => "0.08.00d (/134b481; Jun 17 2018 02:17:51)"
	"Config:NCP:DriverName" => "spinel"
	"NCP:HardwareAddress" => [0000000000000000]

I tried with the troubleshoot tips from [OpenThread Border Router Build and Configuration](https://openthread.io/guides/border-router/build) 
Verify the Border Router has sufficient power. 
Disconnect and reconnect the NCP board to the Border Router platform.
Verify that the NCP serial device is present as `/dev/ttyACM0`, which is also correctly set in `/etc/wpantund.conf`
Reset the NCP with `$sudo wpanctl reset` only changes the ` "NCP:State" => "uninitialized"`, does not reset to ` "offline" `.

FYI, the Raspberry Pi is running Raspbian Stretch Lite, reference 2018-03-13, hardware is `Revision: a22082`. The openthread ncp firmware is recently built from commit c045440. Occasionally, rebooting the RasPi may help bring the NCP to the ` "offline" ` state, but not always the case. 

Does any one have similar experience? Thanks for sharing your suggestions and solutions.

**Comment by gjc13** [comment]
Would you please paste the log output of wpantund, thanks.

**Comment by yz101-osrm** [comment]
@gjc13 Thanks for spending time on this issue. Here are the status of the wpantund service.

`$sudo service wpantund status `
> ● wpantund.service - wpantund 
>   Loaded: loaded (/etc/systemd/system/wpantund.service; enabled; vendor preset: enabled) 
>   Active: active (running) since Sat 2018-07-14 03:20:37 UTC; 9min ago 
> Main PID: 611 (wpantund) 
>   CGroup: /system.slice/wpantund.service 
>           └─611 /usr/sbin/wpantund -o Daemon:SetDefaultRouteForAutoAddedPrefix true -o IPv6:SetSLAACForAutoAddedPrefix true 

`$grep wpantund` in `/var/log` shows  


>daemon.log:36973:Jul 14 03:20:37 raspberrypi systemd[1]: Started wpantund.
daemon.log:36983:Jul 14 03:20:37 raspberrypi wpantund[611]: wpantund[611]: Starting wpantund 0.08.00d (Jun 17 2018 02:17:51) . . .
daemon.log:36984:Jul 14 03:20:37 raspberrypi wpantund[611]: wpantund[611]: #011BUILD_VERSION = 134b481
daemon.log:36985:Jul 14 03:20:37 raspberrypi wpantund[611]: Starting wpantund 0.08.00d (Jun 17 2018 02:17:51) . . .
daemon.log:36987:Jul 14 03:20:37 raspberrypi wpantund[611]: #011BUILD_VERSION = 134b481
daemon.log:36993:Jul 14 03:20:37 raspberrypi wpantund[611]: Configuration file "/etc/wpantund.conf" read.
daemon.log:36995:Jul 14 03:20:37 raspberrypi wpantund[611]: wpantund[611]: Configuration file "/etc/wpantund.conf" read.
daemon.log:36998:Jul 14 03:20:37 raspberrypi wpantund[611]: wpantund[611]: Ready. Using DBUS bus ":1.14"
daemon.log:36999:Jul 14 03:20:37 raspberrypi wpantund[611]: wpantund[611]: Running as root without dropping privileges!
daemon.log:37000:Jul 14 03:20:37 raspberrypi wpantund[611]: Ready. Using DBUS bus ":1.14"
daemon.log:37001:Jul 14 03:20:37 raspberrypi wpantund[611]: Running as root without dropping privileges!
daemon.log:37348:Jul 14 03:20:42 raspberrypi wpantund[611]: wpantund[611]: SpinelNCPInstance-Protothreads.cpp:414: Requirement Failed (IS_EVENT_FROM_NCP(event) && GetInstance(this)->mInboundHeader == mLastHeader)
daemon.log:37349:Jul 14 03:20:42 raspberrypi wpantund[611]: SpinelNCPInstance-Protothreads.cpp:414: Requirement Failed (IS_EVENT_FROM_NCP(event) && GetInstance(this)->mInboundHeader == mLastHeader)
daemon.log:37357:Jul 14 03:20:43 raspberrypi wpantund[611]: wpantund[611]: Resetting and trying again... (retry 1)
daemon.log:37358:Jul 14 03:20:43 raspberrypi wpantund[611]: Resetting and trying again... (retry 1)
daemon.log:37369:Jul 14 03:20:48 raspberrypi wpantund[611]: wpantund[611]: SpinelNCPInstance-Protothreads.cpp:402: Requirement Failed (event == EVENT_NCP_RESET)
daemon.log:37370:Jul 14 03:20:48 raspberrypi wpantund[611]: SpinelNCPInstance-Protothreads.cpp:402: Requirement Failed (event == EVENT_NCP_RESET)
daemon.log:37375:Jul 14 03:20:49 raspberrypi wpantund[611]: wpantund[611]: Resetting and trying again... (retry 2)
daemon.log:37376:Jul 14 03:20:49 raspberrypi wpantund[611]: Resetting and trying again... (retry 2)
daemon.log:37387:Jul 14 03:20:54 raspberrypi wpantund[611]: wpantund[611]: SpinelNCPInstance-Protothreads.cpp:402: Requirement Failed (event == EVENT_NCP_RESET)
daemon.log:37388:Jul 14 03:20:54 raspberrypi wpantund[611]: SpinelNCPInstance-Protothreads.cpp:402: Requirement Failed (event == EVENT_NCP_RESET)
daemon.log:37389:Jul 14 03:20:54 raspberrypi wpantund[611]: wpantund[611]: Resetting and trying again... (retry 3)
daemon.log:37390:Jul 14 03:20:54 raspberrypi wpantund[611]: Resetting and trying again... (retry 3)
daemon.log:37401:Jul 14 03:20:59 raspberrypi wpantund[611]: wpantund[611]: SpinelNCPInstance-Protothreads.cpp:402: Requirement Failed (event == EVENT_NCP_RESET)
daemon.log:37402:Jul 14 03:20:59 raspberrypi wpantund[611]: SpinelNCPInstance-Protothreads.cpp:402: Requirement Failed (event == EVENT_NCP_RESET)
daemon.log:37403:Jul 14 03:21:00 raspberrypi wpantund[611]: wpantund[611]: The NCP is misbehaving: Repeatedly unable to initialize NCP. Entering fault state.
daemon.log:37404:Jul 14 03:21:00 raspberrypi wpantund[611]: wpantund[611]: State change: "uninitialized" -> "uninitialized:fault"
daemon.log:37405:Jul 14 03:21:00 raspberrypi wpantund[611]: The NCP is misbehaving: Repeatedly unable to initialize NCP. Entering fault state.
daemon.log:37406:Jul 14 03:21:00 raspberrypi wpantund[611]: State change: "uninitialized" -> "uninitialized:fault"
daemon.log:38057:Jul 14 03:33:54 raspberrypi wpantund[611]: wpantund[611]: Experiencing extended insomnia. Resetting internal state.
daemon.log:38058:Jul 14 03:33:54 raspberrypi wpantund[611]: Experiencing extended insomnia. Resetting internal state.
daemon.log:38059:Jul 14 03:33:55 raspberrypi wpantund[611]: wpantund[611]: State change: "uninitialized:fault" -> "uninitialized"
daemon.log:38060:Jul 14 03:33:55 raspberrypi wpantund[611]: State change: "uninitialized:fault" -> "uninitialized"
daemon.log:38061:Jul 14 03:33:55 raspberrypi wpantund[611]: wpantund[611]: NCPInstance: error 0
daemon.log:38062:Jul 14 03:33:55 raspberrypi wpantund[611]: NCPInstance: error 0
daemon.log:38063:Jul 14 03:33:55 raspberrypi wpantund[611]: wpantund[611]: Resetting and trying again... (retry 1)
daemon.log:38064:Jul 14 03:33:55 raspberrypi wpantund[611]: Resetting and trying again... (retry 1)
daemon.log:38065:Jul 14 03:34:00 raspberrypi wpantund[611]: wpantund[611]: SpinelNCPInstance-Protothreads.cpp:402: Requirement Failed (event == EVENT_NCP_RESET)
daemon.log:38066:Jul 14 03:34:00 raspberrypi wpantund[611]: SpinelNCPInstance-Protothreads.cpp:402: Requirement Failed (event == EVENT_NCP_RESET)
daemon.log:38067:Jul 14 03:34:00 raspberrypi wpantund[611]: wpantund[611]: Resetting and trying again... (retry 2)
daemon.log:38068:Jul 14 03:34:00 raspberrypi wpantund[611]: Resetting and trying again... (retry 2)
daemon.log:38080:Jul 14 03:34:06 raspberrypi wpantund[611]: wpantund[611]: SpinelNCPInstance-Protothreads.cpp:402: Requirement Failed (event == EVENT_NCP_RESET)
daemon.log:38081:Jul 14 03:34:06 raspberrypi wpantund[611]: SpinelNCPInstance-Protothreads.cpp:402: Requirement Failed (event == EVENT_NCP_RESET)
daemon.log:38082:Jul 14 03:34:06 raspberrypi wpantund[611]: wpantund[611]: Resetting and trying again... (retry 3)
daemon.log:38083:Jul 14 03:34:06 raspberrypi wpantund[611]: Resetting and trying again... (retry 3)
daemon.log:38084:Jul 14 03:34:11 raspberrypi wpantund[611]: wpantund[611]: SpinelNCPInstance-Protothreads.cpp:402: Requirement Failed (event == EVENT_NCP_RESET)
daemon.log:38085:Jul 14 03:34:11 raspberrypi wpantund[611]: SpinelNCPInstance-Protothreads.cpp:402: Requirement Failed (event == EVENT_NCP_RESET)
daemon.log:38086:Jul 14 03:34:12 raspberrypi wpantund[611]: wpantund[611]: The NCP is misbehaving: Repeatedly unable to initialize NCP. Entering fault state.
daemon.log:38087:Jul 14 03:34:12 raspberrypi wpantund[611]: wpantund[611]: State change: "uninitialized" -> "uninitialized:fault"
daemon.log:38088:Jul 14 03:34:12 raspberrypi wpantund[611]: The NCP is misbehaving: Repeatedly unable to initialize NCP. Entering fault state.
daemon.log:38089:Jul 14 03:34:12 raspberrypi wpantund[611]: State change: "uninitialized" -> "uninitialized:fault"

**Comment by gjc13** [comment]
It seems to me CC2652 is not responding to Spinel protocol, what's the firmware you flash to it?

**Comment by bukepo** [comment]
@yz101-osrm are you still having this issue?

**Comment by yz101-osrm** [comment]
@gjc13 @bukepo Sorry for the belated reply. I just made a fresh build of ncp and checked with `wpantund` on the serial port. The issue still exists. 

> $sudo /usr/local/sbin/wpantund -o Config:NCP:SocketPath /dev/ttyACM3 -o Config:TUN:InterfaceName utun7 -o Daemon:SyslogMask " -info"
wpantund[15115]: Starting wpantund 0.08.00d (Jul 17 2018 12:42:15) . . .
wpantund[15115]: 	SOURCE_VERSION = 0.07.01-240-g9f4e111
wpantund[15115]: 	BUILD_VERSION = 0.07.01-240-g9f4e111
wpantund[15115]: Configuration file "/etc/wpantund.conf" read.
wpantund[15115]: Ready. Using DBUS bus ":1.7"
wpantund[15115]: Running as root without dropping privileges!
wpantund[15115]: SpinelNCPInstance-Protothreads.cpp:414: Requirement Failed (IS_EVENT_FROM_NCP(event) && GetInstance(this)->mInboundHeader == mLastHeader)
wpantund[15115]: Resetting and trying again... (retry 1)
wpantund[15115]: SpinelNCPInstance-Protothreads.cpp:402: Requirement Failed (event == EVENT_NCP_RESET)
wpantund[15115]: Resetting and trying again... (retry 2)
wpantund[15115]: SpinelNCPInstance-Protothreads.cpp:402: Requirement Failed (event == EVENT_NCP_RESET)
wpantund[15115]: Resetting and trying again... (retry 3)
wpantund[15115]: SpinelNCPInstance-Protothreads.cpp:402: Requirement Failed (event == EVENT_NCP_RESET)
wpantund[15115]: The NCP is misbehaving: Repeatedly unable to initialize NCP. Entering fault state.
wpantund[15115]: State change: "uninitialized" -> "uninitialized:fault" `

>$sudo /usr/local/bin/wpanctl -I utun7
wpanctl:utun7> status
utun7 => [
	"NCP:State" => "uninitialized:fault"
	"Daemon:Enabled" => true
	"NCP:Version" => ""
	"Daemon:Version" => "0.08.00d (0.07.01-240-g9f4e111; Jul 17 2018 12:42:15)"
	"Config:NCP:DriverName" => "spinel"
	"NCP:HardwareAddress" => [0000000000000000]
]

**Comment by yz101-osrm** [comment]
@gjc13 The firmware I used was `ot-ncp-ftd` in the `/output/cc2652/bin`, uploaded by the Uniflash, and deselected the binary check-box. This file does not have an `elf` extension.

**Comment by bukepo** [comment]
@yz101-osrm  Have you successfully played with the CLI version?

**Comment by yz101-osrm** [comment]
Apologize that it has been a while.  The problem still exists here. 
@bukepo I flashed two cc2652 boards with `ot-cli-ftd`. Plugging them to a Ubuntu machine here, each cc2652 shows up two `/dev/ttyACM*`, not sure if this is normal, or which port should be used. 
Using `screen` or `putty` to access either of these two COM ports, a terminal opens, but no `>` shows up, neither I can type in any CLI commands.  

I followed [Platform: CC2652 Example](https://github.com/openthread/openthread/tree/master/examples/platforms/cc2652). Compared with cc2538, does it need to add the `.elf` extension for `Uniflash`?
 
Please let me know if other information would be helpful to identify this issue. Thanks for your help.

**Comment by yz101-osrm** [comment]
The NCP also behaves the same. After `wpanctl:utun7> reset', the `wpantund` logs shows
> 
wpantund[5434]: State change: "uninitialized:fault" -> "uninitialized"
wpantund[5434]: SpinelNCPTask.cpp:70: Requirement Failed (Failure while trying to send command)
wpantund[5434]: SpinelNCPTaskSendCommand.cpp:322: Requirement Failed ((mRetVal) == 0)
wpantund[5434]: SendCommand task encountered an error: 7 (0x00000007)
wpantund[5434]: SpinelNCPInstance-Protothreads.cpp:414: Requirement Failed (IS_EVENT_FROM_NCP(event) && GetInstance(this)->mInboundHeader == mLastHeader)
wpantund[5434]: Resetting and trying again... (retry 1)
wpantund[5434]: SpinelNCPInstance-Protothreads.cpp:402: Requirement Failed (event == EVENT_NCP_RESET)
wpantund[5434]: Resetting and trying again... (retry 2)
wpantund[5434]: SpinelNCPInstance-Protothreads.cpp:402: Requirement Failed (event == EVENT_NCP_RESET)
wpantund[5434]: Resetting and trying again... (retry 3)
wpantund[5434]: SpinelNCPInstance-Protothreads.cpp:402: Requirement Failed (event == EVENT_NCP_RESET)
wpantund[5434]: The NCP is misbehaving: Repeatedly unable to initialize NCP. Entering fault state.
wpantund[5434]: State change: "uninitialized" -> "uninitialized:fault"

**Comment by bukepo** [comment]
Did you deselect the binary checkbox as suggested in that README?

**Comment by yz101-osrm** [comment]
@bukepo Yes, I did deselect the binary checkbox. 
I will pull the latest openthread later today, and make another try. Thanks.

**Comment by yz101-osrm** [comment]
I found a conflict of `gcc-arm-none-eabi` compiler on my machine. 
Based on the [Build a Thread network with nRF52840](https://codelabs.developers.google.com/codelabs/openthread-hardware/#1), `$sudo apt-get install -y gcc-arm-none-eabi` installs `15:6.3.1+svn253039-1build1`
In the same guide, the "Install ARM GNU Toolchain" will install `arm-none-eabi-gcc`, version `gcc-arm-none-eabi-7-2018-q2-update`. The instruction also suggests install to the recommended folder, i.e., `${HOME}/opt/`, and "**DO NOT add the toolchain path to the user or system path!**"
Meanwhile, based on the [platforms cc2652](https://github.com/openthread/openthread/tree/master/examples/platforms/cc2652), running `$ ./script/bootstrap` installs `arm-none-eabi-gcc` to the user or system path
`$which arm-none-eabi-gcc`
`/usr/bin/arm-none-eabi-gcc`
 `$arm-none-eabi-gcc --version`
`arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 7-2018-q3-update) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

Can you help to verify which ARM Toolchain you are using to build cc2652? Thank you.

**Comment by yz101-osrm** [comment]
Building has generated a WARNING as below. 
`$ make -f examples/Makefile-cc2652 JOINER=1 > build.log`
`configure: WARNING: using cross tools not prefixed with host triplet
/usr/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/bin/ld: warning: cannot find entry symbol _start; defaulting to 0000000000008000`

`_start` address in not defined and defaulted to 0x8000. Is this the right boot sector?

**Comment by srickardti** [comment]
Hey @yz101-osrm, the virtual machine that I use for building OpenThread has the compiler installed in `/opt/.`:
```
$ which arm-none-eabi-gcc
/opt/arm-gcc/latest/bin/arm-none-eabi-gcc
```

And the version of the toolchain I use is:
```
$ arm-none-eabi-gcc --version
arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 5.4.1 20160609 (release) [ARM/embedded-5-branch revision 237715]
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I do not believe that there is an issue with building with the `7.3.1` toolchain, but I have not verified it.

I have not seen that error you included. Since we are building a `nosys` image, it really shouldn't be looking for `_start`. `_start` is used for loading executable within an operating system. In the bare-metal build we rely on the reset vector to get execution context.

**Comment by ubx-caloca** [comment]
It seems to be an issue of the Openthread stack repo and specific to the cc2652 platform code, it also affects the CLI firmware (cannot type CLI commands on the serial connection).  The issue was reported in https://github.com/openthread/openthread/issues/2959 and there is already a fix, however, it is still not merged in master. Already tested the fix (https://github.com/openthread/openthread/pull/2971/commits/8a194a7601b7f84e036d19bbaf60993bc34be1c6) and it indeed it solves the issue with the CC2652 NCP.

**Comment by jwhui** [comment]
@ubx-caloca, thanks for validating the fix! https://github.com/openthread/openthread/pull/2971 is now merged.

@yz101-osrm, can you try again with the latest OpenThread code on the NCP?

**Comment by yz101-osrm** [comment]
@srickardti  Thanks for the fix! @ubx-caloca  Thanks for the validation.
Thank all for your help! 

I just updated to the commit `f993ba5 [toranj] add test-case for router table (#2970)`. Several progresses are successful here so far. 

- The ot-ncp-ftd and ot-cli-ftd firmware are successfully built and loaded to mutliple cc2652 boards respectively. 
- The CLI devices response in the CLI terminal. 
- The NCP responses with wpantund on a ubuntu machine.  
- The NCP Joiner is correctly initialized as `NCP:State uninitialized`, and successfully `associated` to the CLI Commissioner device, rloc16 is correct, ping meshlocal address is done. 

It somehow gets stuck when a CLI Commissioner add a CLI Joiner. They are built with same make flags `COMMISSIONER=1 JOINER=1`. 

`>commissioner joiner add (joiner eui64) ABCDEF`
`Done`

`>joiner start ABCDEF`
`Done`
`>Join failed [NotFound]`

The **Join failed [NotFound]** message came back after a long wait, over 2 minutes. I also tried with the joiner wildcard instead of eui64, swapped roles and tested on multiple cc2652 boards, all stuck here. @jwhui Can you share any insight? Thanks. 

I will try with the border router next Monday.

**Comment by bukepo** [comment]
@yz101-osrm  Is this still a issue for you?

**Comment by ubx-caloca** [comment]
I'm also getting an error when trying to commissioning using CC2652 boards. 

If I use a CC2652 as NCP for the BR, the commissioning app cannot connect to the BR ( I can see the BR in the app, however, when clicking on it and typing the Commissioner passphrase that I know is correct, I get incorrect password error). 

If I use the CC2652 as a joiner and using either the comm app or node with the commissioner role, the CLI of the joiner locks or get frozen when I type the command "joiner start ABCDEF". I have to reboot the joiner node for the CLI to accept commands again.

I think this issue is related with #176.
