### ISSUE TITLE
make -j problems building from scripts

### ISSUE THREAD

**Issue by DuaneEllis-TI** [openthread/borderrouter#17]
Here:

https://github.com/openthread/borderrouter/blob/master/script/_otbr#L50

In the scripts directory, make is invoked with the number of processors for the "-j" parameter.

On a reduced target such as a Beagle Bone runs out of memory when compiling things. 

* RaspberryPi => 1GIG ram
* BeagleBone => 512MEG ram.

for example:
```
  CXX      wpan-controller/libotbr_web_la-dbus_scan.lo
  CXX      wpan-controller/libotbr_web_la-dbus_ifname.lo
  CXX      wpan-controller/libotbr_web_la-wpan_controller.lo
  CXX      mdns-publisher/libotbr_web_la-mdns_publisher.lo
  CXX      pskc-generator/libotbr_web_la-pskc.lo
  CXX      web-service/libotbr_web_la-web_service.lo
[59433.551382] Out of memory: Kill process 21993 (cc1plus) score 707 or sacrifice child
[59433.559409] Killed process 21993 (cc1plus) total-vm:369304kB, anon-rss:352000kB, file-rss:712kB
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
Makefile:839: recipe for target 'web-service/libotbr_web_la-web_service.lo' failed
make[3]: *** [web-service/libotbr_web_la-web_service.lo] Error 1
Makefile:425: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
Makefile:556: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
Makefile:481: recipe for target 'all' failed
make: *** [all] Error 2
debian@beaglebone:~/borderrouter$
```

**Comment by DuaneEllis-TI** [comment]
Wow - I have not hit this type of problem in a very long time.

It's not really the "-j" option, the BBB does not have enough ram to compile the web_service.cpp file in its present form. End of story, full stop.

The issue really comes down to the BBB having 512K of RAM vrs 1GIG for the Raspberry PI.
Enabling virtual swap space is not really viable here.

At this point, I've split the file up into two parts (A) and (B) ... so the total "translation unit" is smaller.
That said, I think splitting the file into 3 equal sized parts is perhaps better.

I'll know more, as I get further into this.

**Comment by DuaneEllis-TI** [comment]
More detail, these three functions seem to be the beasts from a compiler memory point of view.

void WebServer::HandleHttpRequest()
void WebServer::WebServer() <- The constructor
void WebServer::~WebServer() <- The destructor

**Comment by DuaneEllis-TI** [comment]
I can provide a solution to this when I get some other things lined up.
Basically all that is required is to enable a SWAPFILE ... 
I'm adding a script to the "script" folder to do that.

**Comment by bukepo** [comment]
@DuaneEllis-TI Thanks for sharing the solution. Would you like to submit a PR for this issue?

**Comment by DuaneEllis-TI** [comment]
This can be closed, as it is addressed as part of: https://github.com/openthread/borderrouter/pull/115

**Comment by DuaneEllis-TI** [comment]
Closing.
