### ISSUE TITLE
Inbound traffic not allowed after installing border router dependencies

### ISSUE THREAD

**Issue by tarunsmalviya** [openthread/borderrouter#189]
While installing dependencies required for setting up RPi device as border router, the inbound traffic was disabled automatically. 
Is there anything in bootstrap script which results causing this problem?

I was able to solve this issue after allowing ssh inbound using ufw package. 
Below is the link: https://wiki.ubuntu.com/UncomplicatedFirewall

But I am not clear about the cause of issue.

**Comment by bukepo** [comment]
What version of ubuntu are you testing? The script installed `iptables`. I'm not sure if that could cause a problem.

**Comment by tarunsmalviya** [comment]
@bukepo I am using Raspbian lite version. 
Yes. The script installed iptables. 
You can find the script here: https://github.com/openthread/borderrouter/blob/master/script/bootstrap

**Comment by bukepo** [comment]
Yes, I'm sure it installed iptables, which is required by nat64. However, we didn't encountered this issue before. What's the exact Raspbian version do you use?

**Comment by tarunsmalviya** [comment]
@bukepo 
Version: June 2018 | 2018-06-27-raspbian-stretch-lite.img

**Comment by tarunsmalviya** [comment]
@bukepo 
I tried reinstalling the open thread dependencies again on newly flashed Raspbian image over ssh. When I execute ./script/bootstrap command, it got stuck on message "Processing triggers for systemd (232-25+deb9u2) ..."
<img width="790" alt="screen shot 2018-09-07 at 11 06 17 am" src="https://user-images.githubusercontent.com/9993036/45200522-d9901a00-b28e-11e8-920b-83435a517e2e.png">

After pressing Ctrl+C:
<img width="793" alt="screen shot 2018-09-07 at 11 16 05 am" src="https://user-images.githubusercontent.com/9993036/45200668-7c489880-b28f-11e8-8219-db5b5ea6f9f2.png">

**Comment by jwhui** [comment]
@tarunsmalviya, did you resolve your issue? If so, can you provide some information on the problem and resolution?

**Comment by tarunsmalviya** [comment]
Yes. The issue was that I was trying to run script by providing internet through Wifi. But it is mentioned in document that we have to provide internet over ethernet.

**Comment by jwhui** [comment]
@tarunsmalviya, glad you resolved your issue, and thanks for reporting back!
