### ISSUE TITLE
Radvd?

### ISSUE THREAD

**Issue by DuaneEllis-TI** [openthread/borderrouter#19]
What is the plan for "off-platform" (ie: off raspberry pi, or beagle bone) devices to find a route to the thread network? What I mean is this:

Consider the following:
* The Thread Network has on-network prefix (T)
* My home office network has prefix (H) [in my case provided by AT&T Uverse
* Thus my BBB (or raspberry pi) has two interfaces with address (H) and (T).

My cellphone, and laptop only have a HOME network prefix (H), how do they find a
route to the Threadnetwork with prefix (T)? 

I was expecting to see a /etc/rdavd.conf setup.

Am I missing something?

**Comment by jwhui** [comment]
This is a topic that the Thread Group's Border Router Best Practices Effort is trying to address.

RAs are certainly a possible solution, but it does not provide a complete solution for all IPv6 environments.  In particular, RAs will not work in environments that employ IPv6 Router Advertisement Guards [RFC 6105](https://tools.ietf.org/html/rfc6105).  Furthermore, RAs only address the "route propagation", but does not address "configuration".

There seems to be significant support for [RFC 7084](https://tools.ietf.org/html/rfc7084), which relies on DHCPv6 Prefix Delegation to obtain an IPv6 Prefix for a given subnet and configure a route at the CPE.  I believe the Border Router Best Practices is looking towards recommending the use of RFC 7084 mechanisms.  Of course, this assumes the environment has an RFC 7084-compliant CPE.

That said, I am not opposed to implementing an RA-based approach.  The various approaches do not have to be mutually exclusive.  It may be useful to have different mechanisms available, especially for experimentation.  Just thought I would summarize some of the discussion around the various approaches so far.

**Comment by DuaneEllis-TI** [comment]
I think putting the RADAV in place with clear warnings/documentation etc that says: SUBJECT TO CHANGE is important

otherwise, cute little example applications are not going to work.

This could/should be done when BR forms a network, and the on-network prefix is known.

**Comment by jwhui** [comment]
I agree.  @bukepo, can you look into using RADVD to advertise the Thread network's prefix?

**Comment by bukepo** [comment]
OK. I will look into it soon.

**Comment by DuaneEllis-TI** [comment]
@bukepo - Any update on this?

-Duane.

**Comment by bukepo** [comment]
Yes, I did some research, but I cannot get enough time to get it done. I might be able to submit PR this week.

**Comment by bukepo** [comment]
It seems linux must turn on certain kernel configurations to accept route information through ICMPv6.

`/proc/sys/net/ipv6/conf/all/accept_ra_pinfo`
`/proc/sys/net/ipv6/conf/all/accept_ra_rt_info_max_plen`

However, I failed to make it work on openwrt, even with these flags on.

@DuaneEllis-TI thoughts?

**Comment by bukepo** [comment]
@DuaneEllis-TI would you like to share more information on this issue?

**Comment by bukepo** [comment]
@DuaneEllis-TI Any comments here?
