### ISSUE TITLE
Start comissioner failed with FeatureNotSupported for CC1352

### ISSUE THREAD

**Issue by jetacpp** [openthread/borderrouter#191]
Hello,
I compiled NCP firmware for CC1352 with the following options enabled, upon flashing (ot-ncp-ftd), I was not able to start commissioner. I need commissioner for devices to join the network. Can you please help ?

> make -f examples/Makefile-cc1352 COMMISSIONER=1 JOINER=1 COAP=1 DNS_CLIENT=1 MTD_NETDIAG=1 BORDER_ROUTER=1 TMF_PROXY=1 UDP_PROXY=1

Wpantund start log:

> wpantund[968]: Starting wpantund 0.08.00d (Sep 12 2018 15:57:24) . . .
> wpantund[968]: 	SOURCE_VERSION = 0.07.01-253-g4eb20ac
> wpantund[968]: 	BUILD_VERSION = 0.07.01-253-g4eb20ac
> wpantund[968]: Configuration file "/etc/wpantund.conf" read.
> wpantund[968]: Ready. Using DBUS bus ":1.232"
> wpantund[968]: Running as root without dropping privileges!
> wpantund[968]: SpinelNCPInstance-Protothreads.cpp:414: Requirement Failed (IS_EVENT_FROM_NCP(event) && GetInstance(this)->mInboundHeader == mLastHeader)
> wpantund[968]: Resetting and trying again... (retry 1)
> wpantund[968]: [-NCP-]: NCP was reset (STATUS_RESET_SOFTWARE, 114)
> wpantund[968]: State change: "uninitialized" -> "offline"
> wpantund[968]: NCP is running "OPENTHREAD/20170716-00819-g20ccd55c; CC1352; Aug 23 2018 13:03:28"
> wpantund[968]: Driver is running "0.08.00d (0.07.01-253-g4eb20ac; Sep 12 2018 15:57:24)"
> wpantund[968]: Network is not joinable
> wpantund[968]: Resetting interface(s). . .
> wpantund[968]: ../util/netif-mgmt.c:530: Requirement Failed ((ret) == 0)
> wpantund[968]: ../util/netif-mgmt.c:530: Requirement Failed ((ret) == 0)
> wpantund[968]: ../util/netif-mgmt.c:530: Requirement Failed ((ret) == 0)
> wpantund[968]: ../util/netif-mgmt.c:530: Requirement Failed ((ret) == 0)
> wpantund[968]: ../util/netif-mgmt.c:530: Requirement Failed ((ret) == 0)
> wpantund[968]: Finished initializing NCP

Wpanctl log:

> wpan0 => [
> 	"NCP:State" => "associated"
> 	"Daemon:Enabled" => true
> 	"NCP:Version" => "OPENTHREAD/20170716-00819-g20ccd55c; CC1352; Aug 23 2018 13:03:28"
> 	"Daemon:Version" => "0.08.00d (0.07.01-253-g4eb20ac; Sep 12 2018 15:57:24)"
> 	"Config:NCP:DriverName" => "spinel"
> 	"NCP:HardwareAddress" => [00124B00189BCE36]
> 	"NCP:Channel" => 22
> 	"Network:NodeType" => "leader"
> 	"Network:Name" => "DemoThread"
> 	"Network:XPANID" => 0x5CD37A61E281D491
> 	"Network:PANID" => 0xEE87
> 	"IPv6:MeshLocalAddress" => "fd5c:d37a:61e2:0:8bf9:88b4:55b1:31d2"
> 	"IPv6:MeshLocalPrefix" => "fd5c:d37a:61e2::/64"
> 	"com.nestlabs.internal:Network:AllowingJoin" => false
> ]
> dev@dell:~$ sudo wpanctl commissioner start
> commissioner start failed with error 14. FeatureNotSupported
> dev@dell:~$

**Comment by jwhui** [comment]
The NCP version you are using does not include the proper Commissioner support:
```
"NCP:Version" => "OPENTHREAD/20170716-00819-g20ccd55c; CC1352; Aug 23 2018 13:03:28"
```

Can you try using the latest openthread/openthread master code and see if that helps?

**Comment by jetacpp** [comment]
Hello jwhui,

I cloned a brand new master branch and the NCP version with working commissioner is nowOPENTHREAD/20170716-00882-g5c08fb8e. Appreciate much for your help !

**Comment by jetacpp** [comment]
I apologized for closing the issue too soon,

from wpanctl, I used:

> wpanctl:wpan0> status
> wpan0 => [
> 	"NCP:State" => "associated"
> 	"Daemon:Enabled" => true
> 	"NCP:Version" => "OPENTHREAD/20170716-00882-g5c08fb8e; CC1352; Sep 12 2018 17:40:57"
> 	"Daemon:Version" => "0.08.00d (0.07.01-253-g4eb20ac; Sep 12 2018 15:57:24)"
> 	"Config:NCP:DriverName" => "spinel"
> 	"NCP:HardwareAddress" => [00124B00189BCE36]
> 	"NCP:Channel" => 22
> 	"Network:NodeType" => "leader"
> 	"Network:Name" => "DemoThread"
> 	"Network:XPANID" => 0x5CD37A61E281D491
> 	"Network:PANID" => 0xEE87
> 	"IPv6:LinkLocalAddress" => "fe80::3c70:2f5f:806d:e772"
> 	"IPv6:MeshLocalAddress" => "fd5c:d37a:61e2:0:8bf9:88b4:55b1:31d2"
> 	"IPv6:MeshLocalPrefix" => "fd5c:d37a:61e2::/64"
> 	"com.nestlabs.internal:Network:AllowingJoin" => false
> ]
> wpanctl:wpan0> commissioner start
> Commissioner started
> wpanctl:wpan0> commissioner joiner-add * 999 Omega01
> Added Joiner (*), timeout:999, PSKd:"Omega01"
> 

Then from joiner node, I attempt otJoinerStart() with my pre shared key, after a few minutes

on wpantund side, I see it crashed, I have repeated this 3 times:

> wpantund[23044]: Starting wpantund 0.08.00d (Sep 12 2018 15:57:24) . . .
> wpantund[23044]: 	SOURCE_VERSION = 0.07.01-253-g4eb20ac
> wpantund[23044]: 	BUILD_VERSION = 0.07.01-253-g4eb20ac
> wpantund[23044]: Configuration file "/etc/wpantund.conf" read.
> wpantund[23044]: Ready. Using DBUS bus ":1.270"
> wpantund[23044]: Running as root without dropping privileges!
> wpantund[23044]: SpinelNCPInstance-Protothreads.cpp:414: Requirement Failed (IS_EVENT_FROM_NCP(event) && GetInstance(this)->mInboundHeader == mLastHeader)
> wpantund[23044]: Resetting and trying again... (retry 1)
> wpantund[23044]: SpinelNCPInstance-Protothreads.cpp:402: Requirement Failed (event == EVENT_NCP_RESET)
> wpantund[23044]: Resetting and trying again... (retry 2)
> wpantund[23044]: SpinelNCPInstance-Protothreads.cpp:402: Requirement Failed (event == EVENT_NCP_RESET)
> wpantund[23044]: Resetting and trying again... (retry 3)
> wpantund[23044]: [-NCP-]: NCP was reset (STATUS_RESET_SOFTWARE, 114)
> wpantund[23044]: State change: "uninitialized" -> "offline"
> wpantund[23044]: NCP is running "OPENTHREAD/20170716-00882-g5c08fb8e; CC1352; Sep 12 2018 17:40:57"
> wpantund[23044]: Driver is running "0.08.00d (0.07.01-253-g4eb20ac; Sep 12 2018 15:57:24)"
> wpantund[23044]: Network is not joinable
> wpantund[23044]: State change: "offline" -> "offline:commissioned"
> wpantund[23044]: Finished initializing NCP
> wpantund[23044]: AutoResume is enabled. Trying to resume.
> wpantund[23044]: NCP is commissioned. Resuming...
> wpantund[23044]: State change: "offline:commissioned" -> "associating"
> wpantund[23044]: State change: "associating" -> "associated"
> wpantund[23044]: Node type change: "unknown" -> "leader"
> wpantund[23044]: SpinelNCPInstance-Protothreads.cpp:232: Requirement Failed (IS_EVENT_FROM_NCP(event) && GetInstance(this)->mInboundHeader == mLastHeader)
> wpantund[23044]: NCP is misbehaving or unresponsive
> wpantund[23044]: State change: "associated" -> "uninitialized"
> wpantund[23044]: Taking interface(s) down. . .
> wpantund[23044]: SpinelNCPInstance-Protothreads.cpp:414: Requirement Failed (IS_EVENT_FROM_NCP(event) && GetInstance(this)->mInboundHeader == mLastHeader)
> wpantund[23044]: Resetting and trying again... (retry 1)
> wpantund[23044]: SpinelNCPInstance-Protothreads.cpp:402: Requirement Failed (event == EVENT_NCP_RESET)
> wpantund[23044]: Resetting and trying again... (retry 2)
> wpantund[23044]: SpinelNCPInstance-Protothreads.cpp:402: Requirement Failed (event == EVENT_NCP_RESET)
> wpantund[23044]: Resetting and trying again... (retry 3)
> wpantund[23044]: SpinelNCPInstance-Protothreads.cpp:402: Requirement Failed (event == EVENT_NCP_RESET)
> wpantund[23044]: The NCP is misbehaving: Repeatedly unable to initialize NCP. Entering fault state.
> wpantund[23044]: State change: "uninitialized" -> "uninitialized:fault"
>

**Comment by bukepo** [comment]
@jetacpp This might be caused by missing hardware acceleration of ECC. Could you please try the posix-app mode, so that CC1352 only works as radio transceiver?
You may refer to https://github.com/openthread/openthread/blob/32d6eec5fd486e6b0bb50268c2374bff5d8c7059/src/posix/README.md

**Comment by bukepo** [comment]
@jetacpp any good news?

**Comment by jwhui** [comment]
Closing stale issue.
