### ISSUE TITLE
How to restore normal RPi Wifi settings

### ISSUE THREAD

**Issue by tarunsmalviya** [openthread/borderrouter#192]
After building RPi as border router, the Wifi settings are changed. As per installation guide, it becomes an access point. Instead I want to connect RPi to another router.

Can anyone help me out regarding this.

Thanks!

**Comment by bukepo** [comment]
Could you please try setup with `NETWORK_MANAGER=0 ./script/setup`?

**Comment by jwhui** [comment]
Closing stale issue.
