### ISSUE TITLE
otbr-commissioner only working when debug_level>=7

### ISSUE THREAD

**Issue by matteoscordino** [openthread/borderrouter#193]
I know this might be a bit of an extreme case, but we are trying to use otbr-commissioner as external commissioner to commission devices on a Silicon Labs border router.
This is because we haven't found anywhere guidance on how to implement our own external commissioner (the official Thread Commissioning white paper is too abstract to use as implementation guideline).
Important note: the whole commissioning chain works when we use the Thread Commissioning App for android as the external commissioner.

Anyway, using the code in commit 276d3682e5ff1ad0990feeea4b80a72abdc5568b we manage to commission a joiner if the command line debugLevel parameter is >= 7 (i.e. print everything including mbedtls output). It works reliably, but even just redirecting stderr to /dev/null will make it fail.

We never manage to commission with the latest commit (1b695ba322624f6642a7b07adda0454bbcf7b8c5), not even if we enable debug output.

In all cases, petitioning works and the joiner starts communication with otbr-commissioner.

The general architecture is that otbr-commissioner runs on the Border Router, talks to Silicon Labs' commissioning-proxy (i.e. the agent) which in turn uses a SiLabs EFR32 as NCP.
A MED is trying to join.

Here is an example output from a failed session (note: we added a debug line to print the coap payload in SendCoap)

> otbr-commissioner[4975]: agent-address: 10.0.20.144
otbr-commissioner[4975]: agent-port: 49191
otbr-commissioner[4975]: connecting...
otbr-commissioner[4975]: connecting: ssl-setup
otbr-commissioner[4975]: xpanid: 8D089926734E2573
otbr-commissioner[4975]: networkname: [MANUALLY REMOVED]
otbr-commissioner[4975]: passphrase: [MANUALLY REMOVED]
otbr-commissioner[4975]: note: calculating PSKc
otbr-commissioner[4975]: pskc: FE58229E83DE0D73756C04DAB43F509E
otbr-commissioner[4975]: connect: perform handshake
otbr-commissioner[4975]: connect: CONNECTED!
otbr-commissioner[4975]: COMM_PET.req: start
otbr-commissioner[4975]: COMM_PET.req: send
otbr-commissioner[4975]: SendCoap: [4202B94E0001B163026370FF0A0A4F70656E546872656164]
otbr-commissioner[4975]: SendCoap: ssl-write-lenth: 24
otbr-commissioner[4975]: COMM_PET.rsp: start
otbr-commissioner[4975]: COMM_PET.rsp: ignore-tilv: 10
otbr-commissioner[4975]: COMM_PET.rsp: session-id=21
otbr-commissioner[4975]: COMM_PET.rsp: state=accepted
otbr-commissioner[4975]: COMM_PET.rsp: complete
otbr-commissioner[4975]: COMM_PET.req: complete
otbr-commissioner[4975]: COMMISSIONER_SET.req: start
otbr-commissioner[4975]: COMMISSIONER_SET.req: session-id=21
otbr-commissioner[4975]: JOINER: Allow any ingore hashmac
otbr-commissioner[4975]: steering-len: 15
otbr-commissioner[4975]: steering-hex: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
otbr-commissioner[4975]: COMMISSIONER_SET.req: coap-uri: c/cs
otbr-commissioner[4975]: COMMISSIONER_SET.req: sent
otbr-commissioner[4975]: SendCoap: [4202B94F0002B163026373FF0B020015080FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF]
otbr-commissioner[4975]: SendCoap: ssl-write-lenth: 33
otbr-commissioner[4975]: COMMISSIONER_SET.rsp: start
otbr-commissioner[4975]: COMMISSIONER_SET.rsp: state=ready
otbr-commissioner[4975]: COMMISSIONER_SET.rsp: complete
otbr-commissioner[4975]: CommissionerServe: start
otbr-commissioner[4975]: commissioner-serve: device-pskd=[MANUALLY REMOVED]
otbr-commissioner[4975]: DTLS PSK:: 0000: 42 4c 55 45 42 45 4c 4c
otbr-commissioner[4975]: DTLS bound to port 49192.
otbr-commissioner[4975]: CommissionerServe: Tick..
otbr-commissioner[4975]: COMM_KA.req: send
otbr-commissioner[4975]: SendCoap: [4202B9500300B163026361FF1001010B020015]
otbr-commissioner[4975]: SendCoap: ssl-write-lenth: 19
otbr-commissioner[4975]: COMM_KA.rsp: start
otbr-commissioner[4975]: COMM_KA.rsp: state=ready
otbr-commissioner[4975]: COMM_KA.rsp: complete
otbr-commissioner[4975]: CommissionerServe: Tick..
otbr-commissioner[4975]: CommissionerServe: Tick..
otbr-commissioner[4975]: CommissionerServe: Tick..
otbr-commissioner[4975]: CommissionerServe: Tick..
otbr-commissioner[4975]: CommissionerServe: Tick..
otbr-commissioner[4975]: CommissionerServe: Tick..
otbr-commissioner[4975]: CommissionerServe: Tick..
otbr-commissioner[4975]: CommissionerServe: Tick..
otbr-commissioner[4975]: CommissionerServe: Tick..
otbr-commissioner[4975]: CommissionerServe: Tick..
otbr-commissioner[4975]: CommissionerServe: Tick..
otbr-commissioner[4975]: CommissionerServe: Tick..
otbr-commissioner[4975]: CommissionerServe: Tick..
otbr-commissioner[4975]: CommissionerServe: Tick..
otbr-commissioner[4975]: JoinerPort: 61616
otbr-commissioner[4975]: Router locator: 0
otbr-commissioner[4975]: Encapsulation: 417 bytes for port: 49192
otbr-commissioner[4975]: DEST: 0.0.0.0
otbr-commissioner[4975]: CommissionerServe: Tick..
otbr-commissioner[4975]: COMM_KA.req: send
otbr-commissioner[4975]: SendCoap: [4202B9510400B163026361FF1001010B020015]
otbr-commissioner[4975]: SendCoap: ssl-write-lenth: 19
otbr-commissioner[4975]: COMM_KA.rsp: start
otbr-commissioner[4975]: COMM_KA.rsp: state=ready
otbr-commissioner[4975]: COMM_KA.rsp: complete
otbr-commissioner[4975]: Trying to accept connection...
otbr-commissioner[4975]: DTLS handshaking...
otbr-commissioner[4975]: DTLS handshake failed: -0x6a80!
otbr-commissioner[4975]: CommissionerServe: Tick..
otbr-commissioner[4975]: DTLS session destroyed: 4.
otbr-commissioner[4975]: relay from: 127.0.0.1
otbr-commissioner[4975]: RELAY_tx.req: send
otbr-commissioner[4975]: SendCoap: [5202B9520500B163027478FF113C16FEFD0000000000000000002F030000230000]
otbr-commissioner[4975]: SendCoap: ssl-write-lenth: 92
otbr-commissioner[4975]: CommissionerServe: Tick..
otbr-commissioner[4975]: JoinerPort: 61616
otbr-commissioner[4975]: Router locator: 0
otbr-commissioner[4975]: Encapsulation: 449 bytes for port: 49192
otbr-commissioner[4975]: DEST: 0.0.0.0
otbr-commissioner[4975]: CommissionerServe: Tick..
otbr-commissioner[4975]: Trying to accept connection...
otbr-commissioner[4975]: DTLS handshaking...
otbr-commissioner[4975]: DTLS handshake pending: -0x6900.
otbr-commissioner[4975]: CommissionerServe: Tick..
otbr-commissioner[4975]: DTLS session[8] alive.
otbr-commissioner[4975]: relay from: 127.0.0.1
otbr-commissioner[4975]: RELAY_tx.req: send
otbr-commissioner[4975]: SendCoap: [5202B9530600B163027478FF11FF01B516FEFD000000000000000101A80200019C]
otbr-commissioner[4975]: SendCoap: ssl-write-lenth: 471
otbr-commissioner[4975]: CommissionerServe: Tick..
otbr-commissioner[4975]: DTLS session[8] alive.
otbr-commissioner[4975]: relay from: 127.0.0.1
otbr-commissioner[4975]: RELAY_tx.req: send
otbr-commissioner[4975]: SendCoap: [5202B9540700B163027478FF11C116FEFD000000000000000200B40C0000A80002]
otbr-commissioner[4975]: SendCoap: ssl-write-lenth: 225
otbr-commissioner[4975]: CommissionerServe: Tick..
otbr-commissioner[4975]: DTLS session[8] alive.
otbr-commissioner[4975]: relay from: 127.0.0.1
otbr-commissioner[4975]: RELAY_tx.req: send
otbr-commissioner[4975]: SendCoap: [5202B9550800B163027478FF111916FEFD0000000000000003000C0E0000000003]
otbr-commissioner[4975]: SendCoap: ssl-write-lenth: 57
otbr-commissioner[4975]: CommissionerServe: Tick..
otbr-commissioner[4975]: DTLS session[8] alive.
otbr-commissioner[4975]: CommissionerServe: Tick..
otbr-commissioner[4975]: DTLS session[8] alive.
otbr-commissioner[4975]: CommissionerServe: Tick..
otbr-commissioner[4975]: DTLS session[8] alive.
otbr-commissioner[4975]: CommissionerServe: Tick..
otbr-commissioner[4975]: DTLS session[8] alive.
otbr-commissioner[4975]: CommissionerServe: Tick..
otbr-commissioner[4975]: DTLS session[8] alive.
otbr-commissioner[4975]: CommissionerServe: Tick..
otbr-commissioner[4975]: DTLS session[8] alive.
otbr-commissioner[4975]: CommissionerServe: Tick..
otbr-commissioner[4975]: DTLS session[8] alive.

**Comment by bukepo** [comment]
We were testing with the default debug level, which should be 6. There's some big code cleaning up after the old commit you provided. And we'd prefer focusing on the latest version. Could you please try the latest commissioner and attach logs?

**Comment by matteoscordino** [comment]
Of course, will do in a minute. 

Meanwhile, it seems that on the old version things start working even without debug output if I add a delay in `dtls_mbedtls.cpp`, in the `void MbedtlsServer::Process(const fd_set &aReadFdSet, const fd_set &aWriteFdSet, const fd_set &aErrorFdSet)` method.
It definitely looks like a race condition on the file descriptor, similar to issue https://github.com/openthread/borderrouter/issues/87 

Here is the modification I made:
```{
    for (SessionSet::iterator it = mSessions.begin();
         it != mSessions.end();
         ++it)
    {
        MbedtlsSession *session = *it;
        int             fd = session->GetFd();

        usleep(500*1000);                       ///< ugly ugly kludge

        if (FD_ISSET(fd, &aReadFdSet))
        {
            otbrLog(OTBR_LOG_INFO, "DTLS session [%d] become readable.", fd);
            session->Process();
        }
    }

    ProcessServer(aReadFdSet, aWriteFdSet, aErrorFdSet);

    (void)aErrorFdSet;
}

```

**Comment by matteoscordino** [comment]
Attached is a log from the version in HEAD. This is with full debug output and it still doesn't work.
To summarise:
- commit 276d368 does not work out-of-the-box if debug out is disabled or piped to /dev/null
- commit 276d368 works out-of-the-box if debug out is maxed out
- commit 276d368 works regardless of debug level if I add a 500ms sleep before checking the DTLS fs
- HEAD does not work in any case

It definitely looks like a race condition like the one @DuaneEllis-TI found in #87 

[new_otbr.log](https://github.com/openthread/borderrouter/files/2392083/new_otbr.log)

**Comment by bukepo** [comment]
@matteoscordino could you please try #196 ?

**Comment by matteoscordino** [comment]
Just tried, similar behaviour...
 
[otbr_from_pr196.log](https://github.com/openthread/borderrouter/files/2393874/otbr_from_pr196.log)

**Comment by bukepo** [comment]
@matteoscordino we have several enhancements recently, have you tried the latest code?

**Comment by bukepo** [comment]
Close stale issue.
