### ISSUE TITLE
How can I include more features in Web GUI?

### ISSUE THREAD

**Issue by tarunsmalviya** [openthread/borderrouter#201]
I want to include more features in Web GUI like showing details of child, routers in network, commissioner support, etc.
Can you please help me where to start form.

**Comment by tarunsmalviya** [comment]
@gjc13 Can you explain how can I update the current installed OTBR without affecting current configurations.

**Comment by gjc13** [comment]
> @gjc13 Can you explain how can I update the current installed OTBR without affecting current configurations.
You can checkout to the local branch, then
```
./bootstrap
./configure
make
```
You will find updated `otbr-agent` and `otbr-web` executable at `src/agent/otbr-agent` and `src/web/otbr-web` and they will not override your installed binary in $PATH.
