### ISSUE TITLE
[docker] add check for Dockerfile

### ISSUE THREAD

**Issue by bukepo** [openthread/borderrouter#204]
**Is your feature request related to a problem? Please describe.**
There's no guarantee for the Dockerfile in our CI. 

**Describe the solution you'd like**
A specific check for this file.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by gjc13** [comment]
Added a basic docker build check in [pull request](https://github.com/openthread/borderrouter/pull/206)

**Comment by jwhui** [comment]
Resolved by #206.
