### ISSUE TITLE
Openthread Border Router setup script error

### ISSUE THREAD

**Issue by jsnayak** [openthread/borderrouter#207]
I  started the set-up of the border router on a RPi3 using Raspbian lite 2018-06-27-raspbian-stretch-lite. I followed the basic steps as instructed.
sudo apt-get update
sudo apt-get install git
git clone https://github.com/openthread/borderrouter.git
cd borderrouter
./script/bootstrap
./script/setup

The setup script never successfully completed. It stopped with the error:
error: Failed to enable unit: File /etc/systemd/system/wpantund.service already exists

I looked it up and saw the issue reported earlier in https://github.com/openthread/borderrouter/issues/150
Hoping to get it to work, I rolled back to 2018-03-13-raspbian-stretch-lite but I am still facing the same error.

1. My raspberry pi is connected to a 5V 2.4A power supply, the country has been set to IN. 
2. I am directly executing all the commands on the RPi using a connected monitor and keyboard. 
3. Result to the command uname -a is as below
    Linux raspberrypi 4.9.80-v7+ #1098 SMP Fri Mar 9 19:11:42 GMT 2018 armv71 GNU/Linux
4. Using cat /proc/cpuinfo I confirmed the hardware revision version as a22082 which is a Pi 3 Model B. 
5. I am in the master branch of borderrouter and the commit ID is 1c77f02d39974807e37cd892785afd5098e41d15
6. I have not attached any NCP to the RPi as yet
7. The /etc/systemd/system/wpantund.service shows the path as usr/sbin/wpantund . I checked this path and wpantund is present in the path.
8. By manually running script/server, only avahi-daemon.service and otbr-web.service are up as seen in sudo systemctl status

I am unable to get a clue why this is happening consistently. I have tried border router install several times till now. Any suggestions for this resolution?

**Comment by bukepo** [comment]
Did you test on a fresh install on RPi3?

**Comment by jsnayak** [comment]
Bukepo,

Yes, I formatted the sd card and used etcher on windows to install the raspbian-lite. Once that was done, I directly tried the border router install.

**Comment by jwhui** [comment]
@jsnayak, thanks for raising this issue. While I have reproduced the error message, OTBR should be fully installed and running.

One thing you may need to do is modify the `/etc/wpantund.conf` file so that `Config:NCP:SocketPath` points to the proper "/dev/<serial>" device that shows up for your NCP.

After updating `/etc/wpantund.conf`, the easiest thing to do is issue a `sudo reboot`. After reboot, you should use `ifconfig` to confirm if the `wpan0` interface shows up.

In the mean time, we'll take a closer look at why the error message is occurring.

**Comment by jsnayak** [comment]
jwhui,

Thank you for the clarification, I will proceed with the border router testing even if the failed message is generated.

**Comment by jwhui** [comment]
@bukepo, any thoughts on the error message above?

**Comment by bukepo** [comment]
I will look into this issue today.
