### ISSUE TITLE
Docker build failure with etc/Dockerfile 

### ISSUE THREAD

**Issue by sujaykg** [openthread/borderrouter#208]
Hi,

I  used etc/Dockerfile  to build and encountered following errors.

Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [1926 B]
Err:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Get:2 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic/universe Sources [11.5 MB]
Get:6 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:7 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic-updates/universe Sources [115 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [10.8 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [711 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [517 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [6161 B]
Get:15 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [2975 B]
Reading package lists...
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'http://security.ubuntu.com/ubuntu bionic-security InRelease' is not signed.
The command '/bin/sh -c apt-get -y update' returned a non-zero code: 100

**Comment by gjc13** [comment]
Can you run `sudo apt-get update` on your host machine?
I guess your network need an extra login procedure in browser.

**Comment by sujaykg** [comment]
Thank you . I switched to  a my  PC to resolve the issues . the proxy setup wasn't helping and i didnt want to spend much time resolving proxy issue.
