### ISSUE TITLE
It would be good to have a commissioning example.

### ISSUE THREAD

**Issue by DuaneEllis-TI** [openthread/borderrouter#21]
Not sure where this goes - but in the total system level documentation these things are missing:

a) How to use the Thread Commissioning app to configure the border router it self.

b) How to "de-commission" the Border Router - sort of "factory reset" back to not-commissioned state.

c) starting with the commissioned border router, but it is a singleton. Example should show how to configure a CLI device to act as joiner, and then commission that CLI device with the Commissioning app.

As a general outline:

Step 1 - Create a network using the CLI example.
Step 2 - Using the BR-WEB-SERVICE - Join that network.
Step 3 - Use the Openthread Commissioning Application to find the border router.
Step 4 - Select and tap on the OpenThread Border Router
Step 5 - The Commissioning App requests a pass phrase

What needs to be documented is: Where/how is this pass phrase created.

Same would apply to a CLI device that you want to "join/commission"

**Comment by Vyrastas** [comment]
@DuaneEllis-TI 

Seems like the only thing here that's missing from https://openthread.io/guides/border_router/ is

b) How to "de-commission" the Border Router - sort of "factory reset" back to not-commissioned state.

Can you check the updated docs and confirm?

**Comment by jwhui** [comment]
Closing stale issue.
