### ISSUE TITLE
Unable to commission

### ISSUE THREAD

**Issue by vervaekejonathan** [openthread/borderrouter#213]
I'm following (literaly) the guide (https://openthread.io/guides/border-router/external-commissioning)
Everything seems to work, up to the part where the commissioning happens.

You can see below what commands are used to form the network (same as in documentation)

> pi@raspberrypi:~ $ ./pskc J01NME DEAD1111DEAD2222 OpenThreadGuide
198886f519a8fd7c981fee95d72f4ba7
> pi@raspberrypi:~ $ sudo wpanctl setprop Network:PSKc --data 198886f519a8fd7c981fee95d72f4ba7
> pi@raspberrypi:~ $ sudo wpanctl form "OpenThreadGuide"
> Forming WPAN "OpenThreadGuide" as node type "router"
> Successfully formed!
> pi@raspberrypi:~ $ sudo wpanctl status
> wpan0 => [
> 	"NCP:State" => "associated"
> 	"Daemon:Enabled" => true
> 	"NCP:Version" => "OPENTHREAD/20170716-00973-g3fc9b95f; KW41Z; Oct 16 2018 14:49:55"
> 	"Daemon:Version" => "0.08.00d (/47f3212; Oct 18 2018 11:31:34)"
> 	"Config:NCP:DriverName" => "spinel"
> 	"NCP:HardwareAddress" => [4B21070000000000]
> 	"NCP:Channel" => 17
> 	"Network:NodeType" => "leader"
> 	"Network:Name" => "OpenThreadGuide"
> 	"Network:XPANID" => 0x4CB5244CBEE1E209
> 	"Network:PANID" => 0xC17B
> 	"IPv6:MeshLocalAddress" => "fd4c:b524:4cbe:0:6999:e90f:292f:ba0f"
> 	"IPv6:MeshLocalPrefix" => "fd4c:b524:4cbe::/64"
> 	"com.nestlabs.internal:Network:AllowingJoin" => false
> ]
> pi@raspberrypi:~ $ 
> 

When opening up the thread app, i see both ipv4 and ipv6 networks and when trying to connect with the 'J01NME' key, it tells me the password is wrong.

I've tried with other passwords and even with the WEBUI, but it never accepts my passphrase.

When trying to add a node manually via wpanctl, the following error occurs:

> pi@raspberrypi:~ $ sudo wpanctl commissioner joiner-add ABC1230000000000 60 123
> commissioner joiner-add failed with error 4. InvalidForCurrentState
> 

I'm not sure if both are related.

Any advice? Thanks

**Comment by jwhui** [comment]
We'll take a look at the Thread app failure.

As for the manual method, did you issue `wpanctl commissioner start` before `wpanctl commissioner joiner-add`?

**Comment by vervaekejonathan** [comment]
`wpanctl commissioner start` works!

Thanks for looking at the Thread App!

**Comment by jwhui** [comment]
@vervaekejonathan, what hardware are you using for the NCP?

**Comment by vervaekejonathan** [comment]
@jwhui, kw41z 
Thanks!

**Comment by tarunsmalviya** [comment]
I am getting **Join failed [Security]** error while commissioning node through 
NCP.

Following are the command I executed on OTBR:
```
sudo wpanctl commissioner start
sudo wpanctl commissioner joiner-add "*" 120 J01NME
sudo wpanctl permit-join
```

AND Following command in node via cli:
```
ifconfig up
joiner start J01NME
```

Any help will be appreciated.

**Comment by tarunsmalviya** [comment]
@bukepo No. After removing `sudo wpanctl permit-join` command, it worked perfectly.

**Comment by tarunsmalviya** [comment]
Hi,

I am facing the issue regarding commissioner command. I am trying to run the `sudo wpanctl commissioner start` command, but sometimes error occurs as shown in attached screenshot.

![screenshot from 2018-12-26 13-28-38](https://user-images.githubusercontent.com/9993036/50468706-414daa80-09cf-11e9-83a7-72d6d4475ae4.png)

**Comment by jwhui** [comment]
@tarunsmalviya, note that this GitHub issue is closed - please open a new issue so that it can be tracked properly.

In the logs, I also noted that `commissioner start` is failing because the commissioner has already been started.

To help diagnose, can you get and bring the current commissioner state? One possibility is that the commissioner is still in `OT_COMMISSIONER_STATE_PETITION` and is not yet in the `OT_COMMISSIONER_STATE_ACTIVE` state.
