### ISSUE TITLE
nat64 on beaglebone

### ISSUE THREAD

**Issue by d3ads1lence** [openthread/borderrouter#225]
Hi, I am faced some problems with configure nat64 on beaglebone. Studying the scripts folder, I found out that nat was not tested on beaglebone. Could you give me an easy way to do this? Also I want to add that I use docker.

**Comment by jwhui** [comment]
Assuming you are using the default TAYGA configuration, you could test basic functionality by trying to ping an IPv4-Embedded IPv6 Address using the NAT64 well-known prefix of `64:ff9b::/96`. For example, to ping [Google's Public DNS](https://developers.google.com/speed/public-dns/) at `8.8.8.8`, try:
```
    # ping6 64:ff9b::808:808
```

**Comment by d3ads1lence** [comment]
Yes, I tried to ping my PC in a local network. I converted IPv4 into IPv6 and used well-known prefix of 64:ff9b::/96, but this doesn't work. As I understand by default TAYGA not configured on beaglebone so I'm trying to do it now but without any success.
Thanks for yor response.

**Comment by d3ads1lence** [comment]
`# ping6 64:ff9b::808:808`
also doesn't work

**Comment by bukepo** [comment]
Hi @d3ads1lence, You may change https://github.com/openthread/borderrouter/blob/master/examples/platforms/beagleboneblack/default#L40
let `NAT64=1` and setup on a fresh beaglebone. If it doesn't work, please make sure tayga service is running. And note the well-known prefix doesn't support local network, such as 192.168.0.0/16 and 10.0.0.0/8.

**Comment by d3ads1lence** [comment]
@bukepo Hi. I'll check it asap and give you feedback, thanks for your response!

**Comment by d3ads1lence** [comment]
@bukepo Hi,I tested and got some results:
> debian@beaglebone:~$ docker run --sysctl "net.ipv6.conf.all.disable_ipv6=0 \
>         net.ipv4.conf.all.forwarding=1 net.ipv6.conf.all.forwarding=1" \
>         -p 8080:80 --dns=127.0.0.1 -it --volume \
>         /dev/ttyACM0:/dev/ttyACM0 --privileged openthread/otbr \
>         --ncp-path /dev/ttyACM0
WARNING: Localhost DNS setting (--dns=127.0.0.1) may fail in containers.
--ncp-path
NCP_PATH: /dev/ttyACM0
TUN_INTERFACE_NAME: wpan0
NAT64_PREFIX: 64:ff9b::/96
AUTO_PREFIX_ROUTE: true
AUTO_PREFIX_SLAAC: true
Binary file (standard input) matches
Current platform is beagleboneblack
 *** ERROR:  dns64 is not tested under beagleboneblack.

**Comment by bukepo** [comment]
@d3ads1lence could you try entering the container and comment out this line https://github.com/openthread/borderrouter/blob/master/script/_dns64#L41

**Comment by d3ads1lence** [comment]
Sorry for not answering for so long, but now it looks like it works. At least I can ping google.

**Comment by jwhui** [comment]
@d3ads1lence, great to hear things are working. What change did you make to get things working? Was it commenting out the line in the `script/_dns64`?

**Comment by d3ads1lence** [comment]
@jwhui yes, but I download source code and installed borderrouter without Docker. Before that I turned on NAT64 option in the beaglebone config and coomented out line in the script/_dns64.

**Comment by QuincyYoung** [comment]
Hi, I've tried using the "NAT64 option in the beaglebone config and commented out line in the script/_dns64" and whilst I am able to ping 64:ff9b::0808:0808 from the border router (beaglebone), I am still unable to ping the same address from any thread devices. Are there any other changes I must make for the "thread-br-certified-20180819" tag to function correctly?
