### ISSUE TITLE
bug: bash vrs dash issues

### ISSUE THREAD

**Issue by DuaneEllis-TI** [openthread/borderrouter#39]
The LIBCOAP package seems to not play nicely when your shell=dash (the default on some debian platforms) specifically it cannot find the compiler.

The solution is to document that the developer must switch the system shell to bash

**Comment by beriberikix** [comment]
Any idea why it is dependent on ba bash?

**Comment by bukepo** [comment]
I tried
```sh
dash configure --disable-examples
```
It runs successfully. Could you please share more details? @DuaneEllis-TI

**Comment by DuaneEllis-TI** [comment]
Its not the border router or wpantund. 

It is libcoap has major failures on BeagleBone, it is not during the the configure step, it is during the build step that fails.

BTW - have you timed how long things take? In total, I'm seeing about 1hr 15min to perform the bootstrap step, followed by another 1hr or so to do the setup step.

Thus, the cycle time to complete this process takes a while...

**Comment by bukepo** [comment]
Thanks, I tried with dash, it builds successfully. I'm looking forward to the log output.

**Comment by bukepo** [comment]
@DuaneEllis-TI is there any update on this issue?

**Comment by bukepo** [comment]
@DuaneEllis-TI Is this issue still bothering you?

**Comment by DuaneEllis-TI** [comment]
No - I think with some other changes this went away
