### ISSUE TITLE
USB Devices @ BOOT

### ISSUE THREAD

**Issue by DuaneEllis-TI** [openthread/borderrouter#42]
I think this is more of a "development board problem" then an actual product problem.

Many development boards use a USB Serial port for communications to the NCP. Actual physical products will probably reduce cost, and use a dedicated hardware serial port, or SPI interface.

At boot - different platforms enumerate USB interfaces at different rates, and depending upon if a USB hub is present, and what is plugged into the HUB ... as a result: there could be a long time before all USB devices are enumerated.

However, the wpantund service often starts *before* the actual device is starting.

Possible solutions - wrap the wpantund service in a wait-script that waits with a timeout (ie: 10 seconds?) for the serial port to actually appear.

Or do the wait inside of wpantund

Or ... this gets really complicated, configure the service request to wait on the specific USB events but that would be very complex to generalize to all platforms, all devices etc.

**Comment by DuaneEllis-TI** [comment]
BTW - My dirty internal hack is this:

in the super socket open method:
    I have a simple for(;;) loop - limited to (hardcoded) 20 iterations around 
   the lower level C 'open' function.
    If it fails, I call sleep(1second), and try again...
    If it succeeds, I continue on

only after this has failed 20 times, and thus at most 20 seconds - does wpantund die.

this seems to work very nicely.
But don't like the hard coded nature of the 20 retries...

**Comment by bukepo** [comment]
Currently the wpantund service is also governed by systemd, once it fails, it will be restarted at about 5 seconds. Being started before USB device is enumerated seems to be no big issue. Thoughts? @DuaneEllis-TI

**Comment by bukepo** [comment]
@DuaneEllis-TI do you have any more comments on this issue?

**Comment by DuaneEllis-TI** [comment]
Yes, I have a solution that I have been planning on pushing up - it is a hack in wpantund that basically polls the serial port when it fails

The polling rate is every second times a configurable value, the configurable count default value is 20

**Comment by darconeous** [comment]
Why not just rely on systemd?

**Comment by DuaneEllis-TI** [comment]
The problem is different USB types start in different sequences, and with different timing. If you add a HUB, then depending upon which HUB port you are connected to, and what is connected to *other* hub-ports the timing of this varies greatly.

Delaying for X seconds is not deterministic.

What is needed is a systemd rule that says:   Do not start any part of the border router until:

1) Device: /dev/SOMENAME - exists, 
2) and is is group(NAME) and
3) permissions (SOMECOMBO)

At that point, the entire 'udev' set of rules are complete.

I'm not a  systemd expert.

**Comment by DuaneEllis-TI** [comment]
Also note - that in other cases, the creation of the UART interface may - or may not - be done by the UDEV rules,  effectively - I think the best solution might be a small shell script - where the BR does not start unless and until the script returns, 

examples of what that script might do are:

1) updating the flash on the device, or 
2) performing other system level settings (wiggle GPIO to power up the device, etc).
?? Who knows it is very application and platform dependent.

**Comment by bukepo** [comment]
I seems this can be done with **systemd**'s [path unit configuration](https://www.freedesktop.org/software/systemd/man/systemd.path.html). However, since the actual path for device is not fixed, and I'm not sure if this is a general requirement, is it better to leave the task for final distributors? @DuaneEllis-TI

**Comment by DuaneEllis-TI** [comment]
An update - with the current updates to the BeagleBone platform this issue seems to have gone away and/or was resolved on its own - thus I am going to close this.
