### ISSUE TITLE
NAT64/NAT44 documentation issue

### ISSUE THREAD

**Issue by DuaneEllis-TI** [openthread/borderrouter#43]
Hmm - Examples and such generally assume the border router is usable in a 192.168.0.0/16 range

Some routers only provide (default to) a 192.168.0.0/24 range.

Example: DLINK : http://support.dlink.com/emulators/dir601/100NA/lan.html

Others require two sub ranges, Range (A) for the normal access and Range(B) for the guest network range (while others do this another way)

Example: CradelPoint (3G type solution)

http://knowledgebase.cradlepoint.com/articles/Support/Manual-Network-Settings-WiFi-Local-Networks

In this case, they have (require) two non-overlaping IP address ranges, one for internal network and another for the guest network.

Other routers (ie: Netgear provide 10.0.0.0 address ranges [I have this at home])

I think the documentation needs to point this out.

**Comment by bukepo** [comment]
@DuaneEllis-TI Updated in wiki page [NAT64](https://github.com/openthread/borderrouter/wiki/NAT64). Do that solve this issue?
