### ISSUE TITLE
Can't find /etc/wpantund.conf

### ISSUE THREAD

**Issue by campbellwray** [openthread/borderrouter#44]
I have just installed borderrouter on my Raspberry Pi which was previously running wpantund, I followed the installation guide in the wiki and it appears to have worked (can access the web interface), except I cannot connect to the NCP device, my assumption is that this is because wpantund is connecting to the wrong serial device.

The README states that I can configure wpantund with the file`/etc/wpantund.conf`, however this file does not exist.

I'm not sure if this failed to be created because of a bug somewhere or what the issue is.

**Comment by CampbellWray** [comment]
Probably important to note, I am running wpantund 0.07.01 as it is the latest stable release, maybe the config file was introduced after this release?

**Comment by bukepo** [comment]
Did you install wpantund in with sysconfdir=/usr/local? If so, the file would be /usr/local/etc/wpantund.conf.
You probably should configure wpantund with --sysconfdir=/etc.

refer https://github.com/openthread/wpantund/blob/master/INSTALL.md#wpantund-installation-guide

**Comment by CampbellWray** [comment]
That appears to be the issue, is there any difference between it being in /usr/local and /etc, is there any advantage in reinstalling it?

**Comment by CampbellWray** [comment]
So I have reinstalled wpantund and it is now working using `/etc/wpantund.conf` as the config file. I can launch it from the command line using `sudo wpantund` and it works with no issues

When I try to use `sudo systemctl start wpantund otbr-agent otbr-web` to start the processes both `otbr-agent` and `otbr-web` launch fine but not `wpantund`, this can be seen here:

```
pi@raspberrypi:~ $ systemctl list-units | grep "otbr"
otbr-agent.service                                                                                      loaded activating auto-restart Border Router Agent
otbr-web.service                                                                                        loaded active     running      Border Router Web
pi@raspberrypi:~ $ systemctl list-units | grep "wpantund"
(returns nothing)
``` 

Are there any suggestions for fixing this?

**Comment by bukepo** [comment]
I'm not sure if you installed wpantund at `/usr/sbin`. I will update the wiki.
You can also use the following included scripts to setup a border router.

```sh
./script/bootstrap
./script/setup
```

**Comment by CampbellWray** [comment]
No I didn't install it in /usr/sbin, I am not sure how to do that so let me know when you have updated the wiki so I can do that.

**Comment by campbellwray** [comment]
@bukepo I have made some progress with the border router, it all seems to be working properly now.
