### ISSUE TITLE
INFO:  RaspberryPi  V2- Jessie Lite is an ARMv6L, not an ARMv7 image.

### ISSUE THREAD

**Issue by DuaneEllis-TI** [openthread/borderrouter#47]
Update3:  For those who find this via google searches..

Look carefully at your RPi - the difference between the Pi2 vrs Pi3 is subtle, and the numbering is small and sometimes blurry. Raspberry PI v2 is an armv6 platform, not an armv7 - default build tools are currently not included for armv6, only armv7.

update1 a bit more context, this fails in the libcoap step)

a) Update 2 (adding items a,b,c,...) per the Wiki and instructions, this was validated against  Raspberry Pi 3B (running recent Raspbian Jessie Lite)

b) I have that image, the SHA1SUM (note this not the md5sum) I have match the web site.

dad2ba8a228f14e64af7d80e1fd2503facb70c61 *2017-04-10-raspbian-jessie-lite.img
c24a4c7dd1a5957f303193fee712d0d2c0c6372d *2017-04-10-raspbian-jessie-lite.zip

Note that the web site shows the "sha1" of the *ZIP* not the IMG file.

c) If you boot that image, and execute:   'uname -m' you get:  "armv6l"

in the end that output is used to select the binary directory in the thirdparty/nltools binaries are kept.

Specifically, the  host tripplet becomes: armv6l-unknown-linux-gnueabihf

However, the prebuilt has armv7 only.

d) Per this post,  the RPI  Jessie is purposely built this way.

https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=147887

**Conclusion,** you are testing with a different version of the RaspberryPi JessieLite?

If so can you give the details?

```
+ ./bootstrap
patching file repo/Makefile.am
patching file repo/libcoap-1.map
patching file repo/libcoap-1.sym
patching file repo/src/net.c
patching file repo/include/coap/bits.h
patching file repo/src/resource.c

[HINT] You can run 'autogen.sh --clean' to remove all generated files by the autotools.

Found 'autoconf'.
Found 'aclocal'.
Found 'pkg-config'.

Couldn't find 'libtool'!
Found 'libtoolize'.

  --->  Found all needed tools! That's fine.

Generating needed autotools files for libcoap by running autoreconf ...
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force ${ACLOCAL_FLAGS} -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:31: installing './ar-lib'
configure.ac:26: installing './compile'
configure.ac:37: installing './config.guess'
configure.ac:37: installing './config.sub'
configure.ac:18: installing './install-sh'
configure.ac:18: installing './missing'
Makefile.am: installing './INSTALL'
Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'

You can now run 'configure --help' to see possible configuration options.
Otherwise process the configure script to create the makefiles and generated helper files.

./third_party/nlbuild-autotools/repo/scripts/bootstrap: 180: ./third_party/nlbuild-autotools/repo/scripts/bootstrap: cannot open /home/pi/borderrouter/third_party/nlbuild-autotools/repo/tools/host/armv6l-unknown-linux-gnueabihf/bin/libtoolize: No such file
chmod: cannot access ‘/tmp/tmp.bootstrapIQOsmB/libtoolize’: No such file or directory
Can't locate object method "good_version" via package "Autom4te::C4che" at /usr/bin/autom4te line 1002.
aclocal: error: echo failed with exit status: 25

```

**Comment by jwhui** [comment]
It appears that you are using a platform not supported by the existing pre-built GNU autotools.  Can you indicate which platform you are using?

At the same time, you can use the [build](https://github.com/openthread/borderrouter/blob/master/third_party/nlbuild-autotools/repo/tools/packages/build) script to setup pre-build GNU autotools for your platform.

**Comment by DuaneEllis-TI** [comment]
FYI - I updated the original bug description with more details.

The image I am using come from here: https://www.raspberrypi.org/downloads/raspbian/

**Comment by jwhui** [comment]
I believe we are using the same Raspbian image (2017-04-10), but on different hardware.  On my RPI3B:

```bash
pi@raspberrypi:~ $ lscpu
Architecture:          armv7l
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
Model name:            ARMv7 Processor rev 4 (v7l)
CPU max MHz:           1200.0000
CPU min MHz:           600.0000
```

The easiest way to support armv6l is by running the nlbuild-autotools `build` script as I mentioned above on your target hardware.  I would do it myself, but do not currently have an RPI with armv6l.

**Comment by DuaneEllis-TI** [comment]
yea, I'm building this now - what I thought - was a PI-3 is really a PI-2 .... they look nearly identical, with just few changes... and super tiny text  with a blurry model number :-(

**Comment by DuaneEllis-TI** [comment]
Confirmed: That was the problem.

Might be helpful to update the docs and state more explicit that the Raspberry PI-2 has known problems,
they are:  

1)   Lack of the NL tools for arvmv6 - you solution worked (took an hour or more to build ... but it worked)

2)  RPi-2 does not have enough RAM to build the border router

Solution is to enable a larger swap space (ie: 1 gig) it comes standard with a tiny 100MEG swap space.
This is discussed here:  https://raspberrypi.stackexchange.com/questions/70/how-to-set-up-swap-space
The keyword you want to find/search is: /etc/dphys-swapfile

**Comment by jwhui** [comment]
Thanks for following up.  Regarding the lack of NL tools, we'll investigate a way to default to on-host GNU autotools, if available.

**Comment by beriberikix** [comment]
I'm assuming we can x-compile for armv6, so let's make sure to note that somewhere whenever we have the docs in place.

**Comment by beriberikix** [comment]
I'm assuming we can x-compile for armv6, so let's make sure to note that somewhere whenever we have the docs in place.

**Comment by jwhui** [comment]
@DuaneEllis-TI, I'm preparing a PR that allows nlbuild-autotools to use on-host GNU autotools binaries.  This should address the specific issue you ran into here.

@beriberikix, this issue is related to building on host rather than cross-compiling.

**Comment by beriberikix** [comment]
Ah, I see. Would it still be useful to have a way to x-compile  not on the host? Ex. CI or a build farm?
