### ISSUE TITLE
mDNS averts do not start when network is restored

### ISSUE THREAD

**Issue by DuaneEllis-TI** [openthread/borderrouter#49]
steps to reproduce:

1. Start/Form a network.
2. Exit/halt the border router.
3. Restart the border router.
4. On android app - no adverts appear.
5. form a network, you seem to need to change something so change the panid, and networkname
6. Now the border router is advertized

Expected operation:  When BR restarts, the BR should automatically start the mDNS advertising.

Also -(related) from a usability point of view, it would be nice if the commissioning app could direct the user to a web commissioning app if no-network exists on the BR..  otherwise it is dead, and you (the victim/customer/neophite/non-technical person don't know what is going on.
or maybe the BR could avertise something on mDNS that would get the user/victim to the randomly assigned DHCP address of the border router.

**Comment by jwhui** [comment]
Fixed by #67.
