### ISSUE TITLE
without ctags installed - build does not work

### ISSUE THREAD

**Issue by DuaneEllis-TI** [openthread/borderrouter#8]
While the scripts check for CTAGs to be present... (exuberant ctags)

if CTAGs is not actually present, the build does not work very well.

Short term:
   Configure should fail if ctags are not present
Long term:
   It needs a fix.

**Comment by bukepo** [comment]
Yes, `ctags` is required now. We'll improve the configure scripts. Thanks.

**Comment by jwhui** [comment]
Short term fix provided by #11.
