### ISSUE TITLE
Commissioner Proxy Issues

### ISSUE THREAD

**Issue by DuaneEllis-TI** [openthread/borderrouter#81]
I believe there are 2 issues here.

Issue 1 is in the Agent, described here.

Issue 2 is in the embedded side, where the Commissioning Petition is actually handled (there is no provision for duplicate message detection) I believe there should be.
Described here: https://github.com/openthread/openthread/issues/2037

Short Description: The Agent does not seem to handle PROXY requests correctly.
By correctly, I specifically mean with the ability to detect duplicate COAP requests.

Example: 
   https://github.com/openthread/borderrouter/blob/master/src/agent/border_agent.cpp#L102

When a commissioner request is created (example: by the android app) the message is received with both a OPAQUE tag, and a MESSAGE ID - per RFC7252 - Section 2.1 - the Message ID is used to detect duplicates.

However, when the message is forwarded - a call is made to mCoap->NewMessage(), which results in a *NEW* message id for each forwarded message, See:

https://github.com/openthread/borderrouter/blob/master/src/agent/coap_libcoap.cpp#L150 

If the commissioner (ie: The Android App) sends a duplicate CoAP petition, each forwarded message has a "unique message id" - thus when the leader receives the petition - each comes with a unique message id and thus there is *NO* means for the Leader to detect a duplicate request.

I'm not sure of the correct solution here, 

option (1) would be to duplicate (pass through) the message original message ID, 

or 

Option (2) in the agent, mapping of the "android-app-message-id" vrs "proxy-message-id"

Separately, there's an issue with the embedded leader where it does not handles duplicate commissioning  CoAP requests. More generally - in the embedded side I think some common scheme to handle duplicate message detection is an important feature that is missing, while this problem was noticed in the commissioning process at the application layer there is a strong need for duplicate message detection.

**Comment by bukepo** [comment]
@DuaneEllis-TI Thanks for identifying this. Ideally we should involve a fully featured CoAP agent in border router. However, currently the implementation might be too light weight, that is, there is no retransmission nor response cache by the border agent. Border agent replies on the client retransmission and cache from the remote server. `libcoap` is used mostly as a parser. Again, thanks for finding this bug.

I think the option (1) would be a simpler solution for the current design. Would you like to submit a PR for this issue?

**Comment by jwhui** [comment]
@DuaneEllis-TI, has this issue been resolved?
