### ISSUE TITLE
Deprecated bower package

### ISSUE THREAD

**Issue by GiedriusM** [openthread/borderrouter#9]
npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend yarn and webpack for new front-end projects! Please read our blog for more.

**Comment by lanyuwen** [comment]
We also observed the build process would be broken when the local clock was not configured properly and bower wanted to pull angular resource through https. A potential solution would be maintaining needed angular resource within the repository (i.e., put those angular files under third_party/angular).

**Comment by jwhui** [comment]
Resolved by #24.
