### ISSUE TITLE
BUGs: border router commissioning self test script (meshcop) not worked for 3 months

### ISSUE THREAD

**Issue by DuaneEllis-TI** [openthread/borderrouter#94]
Bug 1

In early June - this the border router ./;configure script parameters for the border router changed
See: https://github.com/openthread/openthread/pull/1883

However, the test script: `${borderrouter}/tests/meshcop/meshcop` still uses the old ./configure options

https://github.com/openthread/borderrouter/blob/master/tests/meshcop/meshcop#L72

Bug 2 

Due to the way the scripts are written, a number of things are executed in the background ins ome cass with a & (ampersand) to place it in the background, or they are written using sub shells, or via sudo

if the application "dumps core" for any reason, or exits with a non-zero result - the existing script still exits with a zero result, or - the end result is the error is not captured.

Bug 3  

Scripts that execute in a sub shell, for example in (parens) that have errors are not propigating error/exit values up and resulting in a true error

All of these are addressed here:  https://github.com/openthread/borderrouter/pull/92

**Comment by jwhui** [comment]
Resolved by #92.
